'use strict';
(()=>{
 const n=v=>String(v||'').trim().toUpperCase().replace(/^V-VA-\s*/,'').replace(/[^A-Z0-9]+/g,'');
 function terms(){return String($('query').value||'').split(/[;,\n]+/).map(x=>x.trim()).filter(Boolean);}
 function findRows(){const out=[],seen=new Set();for(const term of terms()){const k=n(term);if(!k)continue;for(const a of state.assets||[]){const assetExact=n(a.name)===k;for(const u of a.units||[]){const fields=[`V-VA-${a.name} ${u.name}`,`${a.name} ${u.name}`,u.name,u.barcode,u.pumpModel,u.type,u.special,u.serial,...((u.customFields||[]).flatMap(f=>[f.label,f.value]))];if(assetExact||fields.some(v=>n(v)===k)||fields.some(v=>n(v).includes(k))){const id=a.id+'|'+u.id;if(!seen.has(id)){seen.add(id);out.push({a,u,term});}}}}}return out;}
 function unitRow(r,check){const id=esc(r.a.id)+'|'+esc(r.u.id),label=esc(('V-VA-'+r.a.name+' '+r.u.name).trim());return `<div class="batchUnit">${check?`<input type="checkbox" data-batch-unit="${id}" checked>`:''}<span><strong>${label}</strong><small>${esc(r.a.module)} · Tool ID ${esc(r.a.name)} · Y ${esc(r.a.y)} / X ${esc(r.a.x)}</small></span><div class="actions"><button type="button" class="light" data-batch-open="${id}">Unit öffnen</button><button type="button" data-batch-today="${id}">Ins Tagesgeschäft</button></div></div>`;}
 function bind(box){box.querySelectorAll('[data-batch-open]').forEach(b=>b.onclick=()=>{const[a,u]=b.dataset.batchOpen.split('|');window.openUnitAt(a,u);});box.querySelectorAll('[data-batch-today]').forEach(b=>b.onclick=()=>{const[a,u]=b.dataset.batchToday.split('|');if(window.addUnitToToday){window.addUnitToToday(a,u);toast('Unit ins Tagesgeschäft übernommen.');paint();}});}
 function paint(){const box=$('multiSearchResults');if(!box)return;const ts=terms();if(!ts.length){box.innerHTML='<p class="hint">Du kannst nach Anlage, Tool-ID oder Unit suchen. Gefundene Units lassen sich direkt öffnen oder ins Tagesgeschäft übernehmen.</p>';return;}const rows=findRows();if(ts.length===1){box.innerHTML=rows.length?`<div class="row"><h3>Gefundene Units · ${rows.length}</h3></div>${rows.map(r=>unitRow(r,false)).join('')}`:'<p class="hint">Keine passende Unit gefunden. Anlagen-Treffer werden darunter weiterhin angezeigt.</p>';bind(box);return;}box.innerHTML=`<div class="row"><h3>Mehrfachsuche · ${rows.length} Unit${rows.length===1?'':'s'}</h3><button id="batchAddToday" ${rows.length?'':'disabled'}>Markierte ins Tagesgeschäft</button></div>${rows.length?rows.map(r=>unitRow(r,true)).join(''):'<div class="empty">Keine Unit-Treffer für die Mehrfachsuche gefunden.</div>'}`;if($('batchAddToday'))$('batchAddToday').onclick=()=>{const checked=[...box.querySelectorAll('[data-batch-unit]:checked')];if(!checked.length)return toast('Bitte mindestens eine Unit markieren.');let count=0;for(const el of checked){const [a,u]=el.dataset.batchUnit.split('|');if(window.addUnitToToday){window.addUnitToToday(a,u);count++;}}toast(`${count} Unit${count===1?'':'s'} ins Tagesgeschäft übernommen.`);paint();};bind(box);}
 const q=$('query');if(q){q.placeholder='z. B. ACS1102, P1 oder V-VA-ACS100 P1';q.addEventListener('input',()=>setTimeout(paint,0));}
 const home=document.querySelector('#home .hint');if(home){const box=document.createElement('section');box.id='multiSearchResults';box.className='multiSearchResults';home.insertAdjacentElement('afterend',box);paint();}
})();
