'use strict';
const cloudNames={none:'Keine Cloud eingerichtet',google:'Google Drive',dropbox:'Dropbox',onedrive:'Microsoft OneDrive'};
function backupStatus(){if(window.Native&&Native.backupStatus)return JSON.parse(Native.backupStatus());return{provider:'none',configured:false,online:navigator.onLine,pending:false,busy:false,error:'',localAt:0,handedAt:0,backups:[]};}
const when=n=>n?new Date(n).toLocaleString('de-DE'):'Noch keine';
function cloudText(s){if(s.busy)return s.direct?'Sicherung wird direkt zu Dropbox hochgeladen …':'Sicherung wird an den Anbieter übergeben …';if(s.error)return s.error;if(s.pending)return s.configured?(s.direct?'Lokal gesichert · Dropbox-Upload ausstehend':'Lokal gesichert · Cloud-Übergabe ausstehend'):'Lokal gesichert · Cloud noch einzurichten';if(s.direct&&s.uploadedAt)return'Lokal und in Dropbox gesichert';if(!s.direct&&s.handedAt)return'An Cloud-App übergeben · Server-Upload dort prüfen';return s.localAt?'Auf diesem Handy gesichert':'Noch keine Sicherung erstellt';}
function effectiveOnline(s){return navigator.onLine!==false&&s&&s.online!==false;}
function updateCloudStatus(){try{const s=backupStatus(),online=effectiveOnline(s),badge=document.querySelector('.offline');badge.textContent=online?'● Online':'● Offline';badge.style.color=online?'#b3d8b0':'#ffb3a7';badge.title=online?'Internetverbindung verfügbar':'Keine Internetverbindung · Änderungen bleiben lokal gespeichert';if($('backupStatusText'))$('backupStatusText').textContent=online?cloudText(s):'Offline – du kannst weiterarbeiten. Änderungen werden automatisch synchronisiert, sobald die Verbindung wieder da ist.';if($('cloudPanel')&&$('modal').open){s.online=online;paintCloudPanel(s);}}catch(e){}}
function cloudPanel(){modal('<div id="cloudPanel"></div>');const s=backupStatus();paintCloudPanel(s);if(s.direct&&s.signedIn&&window.Native&&Native.refreshDropboxBackups){window.dropboxRemoteState={loading:true,backups:[],error:'',restoring:false};paintDropboxPanel(s);Native.refreshDropboxBackups();}}
function paintCloudPanel(s){if(s.direct){paintDropboxPanel(s);return;}$('cloudPanel').innerHTML=`<h2>Cloud &amp; Sicherung</h2><p class="hint">Einmal auswählen und verbinden. Die Einrichtung bleibt auf diesem Handy gespeichert.</p><label for="cloudProvider">Cloud-Anbieter</label><select id="cloudProvider">${Object.entries(cloudNames).map(([k,n])=>`<option value="${k}" ${s.provider===k?'selected':''}>${n}</option>`).join('')}</select><p class="status">${esc(cloudText(s))}</p><p class="hint">Internet: ${s.online?'Online':'Offline'}<br>Letzte lokale Sicherung: ${esc(when(s.localAt))}<br>Letzte Übergabe an Cloud-App: ${esc(when(s.handedAt))}</p>${s.provider!=='none'?`<p>${s.configured?'Sicherungsdatei eingerichtet.':'Sicherungsdatei noch nicht eingerichtet.'}</p><p class="hint">Die ${esc(cloudNames[s.provider])}-App muss installiert und angemeldet sein. Wähle sie in der Android-Dateiauswahl. Falls sie dort nicht erscheint oder keinen dauerhaften Dateizugriff unterstützt, ist die direkte Verbindung auf diesem Handy nicht verfügbar.</p><button id="connectCloud" class="light">${s.configured?'Andere Sicherungsdatei wählen':'Sicherungsdatei einrichten'}</button><p class="hint">Die letzte lokale Sicherung wird an die gewählte Datei übergeben. Spätere Sicherungen ersetzen dort die vorherige Kopie. Lokal bleiben alle Sicherungen erhalten.</p>${s.configured?'<button id="disconnectCloud" class="danger">Verbindung entfernen</button>':''}`:''}<div class="actions" style="margin-top:18px"><button id="backupNow">Jetzt sichern</button><button id="retryCloud" class="light">Übergabe erneut versuchen</button><button id="cancel" class="light">Schließen</button></div><p class="hint">„Online“ zeigt die Internetverbindung. Nach erfolgreicher Dateiübergabe übernimmt die Cloud-App den eigentlichen Upload; dessen Abschluss kann Anlagenbuch nicht bestätigen. Ein erneuter Versuch erfolgt bei geöffneter App sowie beim nächsten Öffnen mit Internet.</p><p class="hint">Dies sind Sicherungen. Arbeits-/Tagesprotokolle werden bei Dropbox-Verbindung zusätzlich automatisch mit den Kollegen abgeglichen und bei einer Wiederherstellung geschützt. Lokale Sicherungen liegen im App-Speicher und werden bei einer Deinstallation gelöscht. Mit „Dateikopie speichern“ kannst du zusätzlich eine unabhängige Kopie ablegen.</p><h3>Lokale Sicherungen (${s.backups.length})</h3>${s.backups.length?s.backups.map(b=>`<div class="record"><strong>${esc(when(b.at))}</strong><div class="actions"><button class="light" data-restore-backup="${esc(b.id)}">Wiederherstellen</button></div></div>`).join(''):'<p class="hint">Noch keine vorhanden.</p>'}`;
 $('cancel').onclick=()=>$('modal').close();$('cloudProvider').onchange=e=>{if(!window.Native||!Native.selectCloud)return toast('Die Cloud-Einrichtung ist in der Android-App verfügbar.');Native.selectCloud(e.target.value);updateCloudStatus();};$('backupNow').onclick=makeBackup;$('retryCloud').onclick=()=>{if(window.Native&&Native.retryCloud)Native.retryCloud();else toast('Bitte in der Android-App öffnen.');};if($('connectCloud'))$('connectCloud').onclick=()=>Native.connectCloud(s.provider);if($('disconnectCloud'))$('disconnectCloud').onclick=()=>{if(confirm('Verbindung entfernen? Lokale Sicherungen und die Cloud-Datei bleiben erhalten.'))Native.disconnectCloud();};
}
function makeBackup(){if(window.Native&&Native.makeBackup){Native.makeBackup(JSON.stringify(state));toast('Lokale Sicherung wird erstellt.');}else toast('Lokale Sicherungen und Cloud-Verbindungen sind in der Android-App verfügbar. Nutze hier „Dateikopie speichern“.');}
document.addEventListener('click',e=>{const b=e.target.closest('[data-restore-backup]');if(b&&window.Native){const raw=Native.readBackup(b.dataset.restoreBackup);$('modal').close();receiveImport(raw);}});
window.cloudChanged=updateCloudStatus;
$('dataTools').onclick=cloudPanel;$('cloudSettings').onclick=cloudPanel;$('backupButton').onclick=makeBackup;
function resumeAllSync(){updateCloudStatus();try{if(window.Native){if(Native.retryCloud)Native.retryCloud();if(Native.syncFaults)Native.syncFaults();if(Native.syncWork)Native.syncWork();}if(window.globalSyncPushNow)window.globalSyncPushNow();}catch(_){}setTimeout(updateCloudStatus,700);setTimeout(updateCloudStatus,2200);}
window.addEventListener('online',resumeAllSync);window.addEventListener('offline',updateCloudStatus);
updateCloudStatus();setInterval(()=>{if(!$('modal').open)updateCloudStatus();if(window.Native&&Native.retryCloud)Native.retryCloud();},60000);
