'use strict';
const num=n=>n===null?'Noch nicht hinterlegt':Number(n).toLocaleString('de-DE',{maximumFractionDigits:8});
const field=n=>n===null?'':String(n).replace('.',',');
const currentAsset=()=>state.assets.find(a=>a.id===selected);
function readingOrder(a,b){return b.date.localeCompare(a.date)||b.id.localeCompare(a.id);}
function assetValueRows(s){
 s=(s&&typeof s==='object')?s:{};
 if(Object.prototype.hasOwnProperty.call(s,'assetValues'))return (Array.isArray(s.assetValues)?s.assetValues:[]).map((v,i)=>({id:String(v&&v.id||('asset-value-'+i)),label:String(v&&v.label||'').trim(),value:v&&v.value!==undefined&&v.value!==null?String(v.value):'',unit:String(v&&v.unit||'').trim()}));
 const rows=[];
 if(s.inlet!==null&&s.inlet!==undefined&&String(s.inlet).trim()!=='')rows.push({id:'legacy-inlet',label:'Stickstoff · Eingangsdruck',value:String(s.inlet).replace('.',','),unit:'bar'});
 return rows;
}
window.getAssetValueRows=assetValueRows;
function assetValueEditor(v,cls='assetValueRow'){return `<div class="${cls}" data-asset-value-id="${esc(v.id||uid())}"><div><label>Bezeichnung</label><input class="assetValueLabel" value="${esc(v.label||'')}" maxlength="100" placeholder="z. B. Stickstoff · Eingangsdruck"></div><div><label>Wert</label><input class="assetValueValue" value="${esc(v.value===undefined||v.value===null?'':String(v.value))}" maxlength="200" placeholder="Nicht hinterlegt"></div><div><label>Einheit</label><input class="assetValueUnit" value="${esc(v.unit||'')}" maxlength="40" placeholder="z. B. bar"></div><button type="button" class="danger assetValueDelete">Feld löschen</button></div>`;}
window.assetValueEditor=assetValueEditor;
function readAssetValues(container){return [...container.querySelectorAll('[data-asset-value-id]')].map(el=>({id:el.dataset.assetValueId||uid(),label:el.querySelector('.assetValueLabel').value.trim(),value:el.querySelector('.assetValueValue').value.trim(),unit:el.querySelector('.assetValueUnit').value.trim()})).filter(x=>x.label);}
window.readAssetValues=readAssetValues;
function canonicalSettings(s){s=(s&&typeof s==='object')?s:{};return {assetValues:assetValueRows(s),lines:(Array.isArray(s.lines)?s.lines:[]).map((l,i)=>({id:String(l&&l.id||('line-'+i)),name:String(l&&l.name||''),value:l&&l.value!==undefined?l.value:null,unit:String(l&&l.unit||'')})),heaters:(Array.isArray(s.heaters)?s.heaters:[]).map((h,i)=>({id:String(h&&h.id||('heat-'+i)),name:String(h&&h.name||''),value:h&&h.value!==undefined?h.value:null})),hint:String(s.hint||'')};}
window.canonicalAssetSettings=canonicalSettings;
function settingRows(s){const rows=assetValueRows(s).filter(v=>v.label);return rows.map(v=>`<div class="settingRow"><span>${esc(v.label)}</span><strong>${v.value!==''?esc(String(v.value))+(v.unit?' '+esc(v.unit):''):'Noch nicht hinterlegt'}</strong></div>`).join('')+(Array.isArray(s.lines)?s.lines:[]).map(l=>`<div class="settingRow"><span>${esc(l.name)}</span><strong>${num(l.value)}${l.value===null?'':' '+esc(l.unit)}</strong></div>`).join('')+(Array.isArray(s.heaters)?s.heaters:[]).map(h=>`<div class="settingRow"><span>Heizung · ${esc(h.name)}</span><strong>${num(h.value)}${h.value===null?'':' °C'}</strong></div>`).join('')+(s.hint?`<p class="equipmentHint">${esc(s.hint)}</p>`:'');}
function renderEquipment(a){
 const readings=[...a.hours].sort(readingOrder),last=readings[0],history=a.settingsHistory,lastChange=history[history.length-1];
 $('equipment').innerHTML=`<nav class="sectionNav" aria-label="Anlagenbereiche"><button class="light" data-jump="settingsSection">Sollwerte</button><button class="light" data-jump="partsSection">Ersatzteile</button><button class="light" data-jump="hoursSection">Betriebsstunden</button><button class="light" data-jump="handlingSection">Hantierungsanweisung</button><button class="light" data-jump="notesSection">Notizen</button></nav>
 <section class="equipmentBox" id="settingsSection"><div class="row"><h2>Sollwerte / Einstellungen</h2><button id="editSettings" class="light">Bearbeiten</button></div><p class="hint">Manuell hinterlegte Vorgaben für diese Anlage.</p>${settingRows(a.settings)}${lastChange?`<p class="hint">Geändert von ${esc(lastChange.author)} · ${esc(new Date(lastChange.at).toLocaleString('de-DE'))}</p>`:''}<button id="settingsHistory" class="light historyButton">Änderungsverlauf (${history.length})</button></section>
 <section class="equipmentBox" id="partsSection"><div class="row"><h2>Ersatzteile (${a.parts.length})</h2><button id="addPart">+ Teil</button></div>${a.parts.length?a.parts.map(p=>`<article class="record"><strong>${esc(p.name)}</strong><p class="hint">Teilenummer: ${p.number?esc(p.number):'Nicht hinterlegt'} · Menge: ${num(p.quantity)}</p>${p.note?`<p class="equipmentHint">${esc(p.note)}</p>`:''}<div class="actions"><button class="light" data-edit-part="${esc(p.id)}">Bearbeiten</button><button class="danger" data-delete-part="${esc(p.id)}">Löschen</button></div></article>`).join(''):'<p class="empty">Noch keine Ersatzteile hinterlegt.</p>'}</section>
 <section class="equipmentBox" id="hoursSection"><div class="row"><h2>Betriebsstunden</h2><button id="addHours">+ Ablesung</button></div><div class="hoursSummary"><strong>${last?num(last.value)+' h':'Noch nicht hinterlegt'}</strong><span>${last?'Zuletzt abgelesen am '+esc(last.date.split('-').reverse().join('.')):'Zählerstand später ergänzen'}</span></div><p class="hint">Abgelesener Zählerstand; wird nicht automatisch hochgezählt. Ein niedrigerer Wert ist nach einem Pumpen- oder Zählerwechsel möglich.</p>${readings.length?`<details><summary>Ableseverlauf (${readings.length})</summary>${readings.map(h=>`<article class="record"><strong>${num(h.value)} h</strong> · ${esc(h.date.split('-').reverse().join('.'))}${h.note?`<p class="equipmentHint">${esc(h.note)}</p>`:''}<div class="actions"><button class="light" data-edit-hours="${esc(h.id)}">Bearbeiten</button><button class="danger" data-delete-hours="${esc(h.id)}">Löschen</button></div></article>`).join('')}</details>`:''}</section>`;
 $('editSettings').onclick=settingsForm;$('settingsHistory').onclick=showSettingsHistory;$('addPart').onclick=()=>partForm();$('addHours').onclick=()=>hoursForm();
}
function finishEquipmentEdit(action,message){if(change(action)){$('modal').close();toast(message);}}
function partForm(id){const a=currentAsset(),p=a.parts.find(p=>p.id===id)||{name:'',number:'',quantity:1,note:''};modal(`<h2>${id?'Ersatzteil bearbeiten':'Ersatzteil hinzufügen'}</h2><p>${esc(a.name)}</p><form id="partForm"><label for="partName">Bezeichnung</label><input id="partName" name="partName" value="${esc(p.name)}" required maxlength="200"><label for="partNumber">Teilenummer (optional)</label><input id="partNumber" name="partNumber" value="${esc(p.number)}" maxlength="200"><label for="partQuantity">Benötigte Menge</label><input id="partQuantity" name="quantity" value="${field(p.quantity)}" inputmode="decimal" required><label for="partNote">Bemerkung (optional)</label><textarea id="partNote" name="note" maxlength="10000">${esc(p.note)}</textarea><div class="actions"><button>Speichern</button><button id="cancel" type="button" class="light">Abbrechen</button></div></form>`);$('partForm').onsubmit=e=>{e.preventDefault();try{const f=e.target.elements,p={id:id||uid(),name:f.partName.value.trim(),number:f.partNumber.value.trim(),quantity:C.decimal(f.quantity.value),note:f.note.value.trim()};if(p.quantity===null)throw Error('Bitte die Menge eintragen.');finishEquipmentEdit(s=>{const rows=s.assets.find(a=>a.id===selected).parts,i=rows.findIndex(p=>p.id===id);if(i<0)rows.push(p);else rows[i]=p;},'Ersatzteil gespeichert.');}catch(e){toast(e.message);}};}
function hoursForm(id){const a=currentAsset(),h=a.hours.find(h=>h.id===id)||{date:today(),value:null,note:''};modal(`<h2>${id?'Ablesung bearbeiten':'Betriebsstunden eintragen'}</h2><p>${esc(a.name)}</p><form id="hoursForm"><label for="hoursDate">Ablesedatum</label><input type="date" id="hoursDate" name="date" value="${esc(h.date)}" required><label for="hoursValue">Zählerstand in Stunden</label><input id="hoursValue" name="hours" value="${field(h.value)}" inputmode="decimal" required placeholder="z. B. 12500"><label for="hoursNote">Hinweis (optional)</label><textarea id="hoursNote" name="note" maxlength="10000" placeholder="z. B. neue Pumpe eingebaut / Zähler gewechselt">${esc(h.note)}</textarea><div class="actions"><button>Speichern</button><button id="cancel" type="button" class="light">Abbrechen</button></div></form>`);$('hoursForm').onsubmit=e=>{e.preventDefault();try{const f=e.target.elements,h={id:id||uid(),date:f.date.value,value:C.decimal(f.hours.value),note:f.note.value.trim()};if(h.value===null)throw Error('Bitte einen Zählerstand eintragen.');finishEquipmentEdit(s=>{const rows=s.assets.find(a=>a.id===selected).hours,i=rows.findIndex(h=>h.id===id);if(i<0)rows.push(h);else rows[i]=h;},'Ablesung gespeichert.');}catch(e){toast(e.message);}};}
function heaterEditor(h){return `<div class="heaterEdit" data-heater="${esc(h.id)}"><label>Heizabschnitt<input class="heatName" value="${esc(h.name)}" required maxlength="100"></label><label>Temperatur-Sollwert (°C)<input class="heatValue" value="${field(h.value)}" inputmode="decimal" placeholder="Noch nicht hinterlegt"></label><button class="danger" type="button" data-remove-heater="${esc(h.id)}">Abschnitt entfernen</button></div>`;}
function lineEditor(l){return `<div class="equipmentLineEdit" data-line-id="${esc(l.id||uid())}"><label>Bezeichnung<input class="equipLineName" value="${esc(l.name||'')}" maxlength="100" placeholder="z. B. N2 Dilution"></label><label>Sollwert<input class="equipLineValue" value="${l.value===null||l.value===undefined?'':esc(String(l.value).replace('.',','))}" inputmode="decimal" placeholder="Nicht hinterlegt"></label><label>Einheit<input class="equipLineUnit" value="${esc(l.unit||'')}" maxlength="40" placeholder="z. B. bar"></label><button class="danger equipLineDelete" type="button">Feld löschen</button></div>`;}
function settingsForm(){
 const a=currentAsset(),s=(a.settings&&typeof a.settings==='object')?a.settings:{},last=a.settingsHistory[a.settingsHistory.length-1],values=assetValueRows(s),lines=(Array.isArray(s.lines)?s.lines:[]).map((l,i)=>({id:l.id||('line-'+i),name:l.name||'',value:l.value,unit:l.unit||''})),heaters=Array.isArray(s.heaters)?s.heaters:[];
 modal(`<h2>Anlagenwerte / Einstellungen bearbeiten</h2><p>${esc(a.name)} · ${esc(a.module)}</p><p class="hint">Alle Anlagenwerte gelten für alle Units dieser Anlage. Bezeichnungen, Werte und Einheiten können frei geändert, ergänzt oder gelöscht werden.</p><form id="settingsForm"><fieldset><legend>Anlagenwerte</legend><div id="assetValueEditors">${values.map(v=>assetValueEditor(v,'assetValueRow')).join('')}</div><button id="addAssetValue" class="light" type="button">+ Anlagenwert hinzufügen</button></fieldset><div class="row settingEditorHeading"><h3>Leitungen / Medien</h3><button id="addLine" class="light" type="button">+ Feld hinzufügen</button></div><div id="lineEditors">${lines.map(lineEditor).join('')}</div><h3>Rohrbegleitheizung</h3><div id="heaterEditors">${heaters.map(heaterEditor).join('')}</div><button id="addHeater" class="light" type="button">+ Heizabschnitt</button><label for="settingsHint" style="margin-top:20px">Hinweise für den Monteur</label><textarea id="settingsHint" name="hint" maxlength="10000">${esc(s.hint||'')}</textarea><label for="settingsAuthor">Geändert von (Name / Kürzel)</label><input id="settingsAuthor" name="author" maxlength="100" required value="${last?esc(last.author):''}"><p class="hint">Änderungen werden mit Name, Zeitpunkt und den eingetragenen Anlagenwerten im Verlauf gespeichert.</p><div class="actions"><button>Speichern</button><button id="cancel" class="light" type="button">Abbrechen</button></div></form>`);
 $('addAssetValue').onclick=()=>{$('assetValueEditors').insertAdjacentHTML('beforeend',assetValueEditor({id:uid(),label:'Neuer Anlagenwert',value:'',unit:''},'assetValueRow'));};
 $('assetValueEditors').onclick=e=>{const b=e.target.closest('.assetValueDelete');if(b&&confirm('Diesen Anlagenwert löschen?'))b.closest('[data-asset-value-id]').remove();};
 $('addLine').onclick=()=>{$('lineEditors').insertAdjacentHTML('beforeend',lineEditor({id:uid(),name:'Neues Feld',value:null,unit:''}));};
 $('lineEditors').onclick=e=>{const b=e.target.closest('.equipLineDelete');if(b&&confirm('Dieses Leitungs-/Medienfeld löschen?'))b.closest('.equipmentLineEdit').remove();};
 $('addHeater').onclick=()=>{if($('heaterEditors').children.length>=100)return toast('Maximal 100 Heizabschnitte.');$('heaterEditors').insertAdjacentHTML('beforeend',heaterEditor({id:uid(),name:'Heizabschnitt '+($('heaterEditors').children.length+1),value:null}));};
 $('heaterEditors').onclick=e=>{const b=e.target.closest('[data-remove-heater]');if(b&&confirm('Diesen Heizabschnitt aus den Sollwerten entfernen?'))b.closest('.heaterEdit').remove();};
 $('settingsForm').onsubmit=e=>{e.preventDefault();try{
   const assetValues=readAssetValues($('assetValueEditors'));
   const lineRows=[...document.querySelectorAll('.equipmentLineEdit')].map(el=>({id:el.dataset.lineId||uid(),name:el.querySelector('.equipLineName').value.trim(),value:C.decimal(el.querySelector('.equipLineValue').value),unit:el.querySelector('.equipLineUnit').value.trim()})).filter(x=>x.name||x.value!==null);
   const heatRows=[...document.querySelectorAll('.heaterEdit')].map(el=>({id:el.dataset.heater,name:el.querySelector('.heatName').value.trim(),value:C.decimal(el.querySelector('.heatValue').value,true)})).filter(x=>x.name||x.value!==null);
   const nextCanon={assetValues,lines:lineRows,heaters:heatRows,hint:$('settingsHint').value.trim()},author=$('settingsAuthor').value.trim();
   if(!author)throw Error('Bitte Name oder Kürzel eintragen.');
   if(JSON.stringify(nextCanon)===JSON.stringify(canonicalSettings(s))){$('modal').close();toast('Keine Anlagenwerte geändert.');return;}
   const nextSettings={...s,inlet:null,assetValues,lines:lineRows,heaters:heatRows,hint:nextCanon.hint};
   finishEquipmentEdit(st=>{const target=st.assets.find(a=>a.id===selected);target.settings=nextSettings;target.settingsHistory=Array.isArray(target.settingsHistory)?target.settingsHistory:[];target.settingsHistory.push({id:uid(),at:new Date().toISOString(),author,values:C.clone(nextSettings)});},'Anlagenwerte und Änderungsverlauf gespeichert.');
 }catch(e){toast(e.message);}};
}
function showSettingsHistory(){const a=currentAsset();modal(`<h2>Änderungsverlauf</h2><p>${esc(a.name)}</p>${a.settingsHistory.length?[...a.settingsHistory].reverse().map(h=>`<article class="record"><strong>${esc(h.author)}</strong><p class="hint">${esc(new Date(h.at).toLocaleString('de-DE'))}</p>${settingRows(h.values)}</article>`).join(''):'<p>Noch keine Sollwerte eingetragen.</p>'}<button id="cancel" class="light">Schließen</button>`);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.jump){const el=$(d.jump);if(el)el.scrollIntoView({behavior:'smooth'});}if(d.editPart)partForm(d.editPart);if(d.editHours)hoursForm(d.editHours);for(const [attr,key,label] of [['deletePart','parts','dieses Ersatzteil'],['deleteHours','hours','diese Ablesung']])if(d[attr]&&confirm(`Möchtest du ${label} löschen?`))change(s=>{const a=s.assets.find(a=>a.id===selected);a[key]=a[key].filter(r=>r.id!==d[attr]);});});
