 'use strict';
const VERSION='3.33';
const CACHE='anlagenbuch-shell-'+VERSION;
const MEDIA_CACHE='anlagenbuch-media-2.85';
const CORE=["/index.html","/app.html","/login.html","/offline-store-235.js","/web-bootstrap-onedrive.js","/sw.js"];
const ASSETS=["/_worker.js","/annex-data.js","/annex-original.jpeg","/app-249.js","/app.html","/batch-search.js","/btf-data.js","/busch-favicon-v220.ico","/busch-icon-192-v220.png","/busch-icon-512-v220.png","/busch-logo.png","/core.js","/default-psa-migration-242.js","/equipment.css","/equipment.js","/global-sync-247.js","/handling-multi-249.js","/help-data.js","/help-image-asset.png","/help-image-cloud.png","/help-image-detail.png","/help-image-fault.png","/help-image-help.png","/help-image-home.png","/help-image-homecurrent.png","/help-image-hours.png","/help-image-linked.png","/help-image-menu.png","/help-image-menucurrent.png","/help-image-multiunits.png","/help-image-picker.png","/help-image-pool.png","/help-image-protocol.png","/help-image-settings.png","/help-image-setup.png","/help-image-todaydone.png","/help-image-todaylist.png","/help-image-unitdetail.png","/help-image-viewer.js","/help-image-widgetcurrent.png","/help-image-work.png","/help.js","/icon-192.png","/icon-512.png","/index.html","/lageplan-gelaende.jpeg","/login.html","/login.js","/manifest.webmanifest","/migrate-local.js","/modul1-original.jpeg","/modul2-original.jpeg","/module1-data.js","/offline-store-235.js","/onedrive-client.js","/onedrive-ui.js","/pc-widget.html","/pool-links.js","/psa/M001.jpg","/psa/M003.jpg","/psa/M004.jpg","/psa/M008.jpg","/psa/M009.jpg","/psa/M010.jpg","/psa/M011.jpg","/psa/M012.jpg","/psa/M013.jpg","/psa/M014.jpg","/psa/M015.jpg","/psa/M017.jpg","/psa/M018.jpg","/psa/M020.jpg","/psa/M021.jpg","/psa/M022.jpg","/psa/M023.jpg","/psa/M024.jpg","/psa/M026.jpg","/psa/WSM001.jpg","/pump-serial-data-247.js","/pump-serial-migration-247.js","/pump-unit-data.js","/qrcode-runtime.js","/repair-bootstrap.js","/seed-preview.js","/settings-menu.css","/settings-menu.js","/siren.wav","/stoerungssirene.mp3","/style.css","/sw.js","/sync-merge.js","/units-248.js","/vendor/jsQR.js","/vendor/pdfjs/pdf.js","/vendor/pdfjs/pdf.worker.js","/web-bootstrap-onedrive.js","/web-pdf-offline-249.js","/web-ui-249.js","/web.css","/widget.js"];
const STATIC_PATHS=new Set(ASSETS);
const INSTALL_ASSETS=ASSETS.filter(p=>p!=="/_worker.js"); // Server-Worker is not browser-side app code
function norm(url){const p=new URL(url,self.location.origin).pathname;return p==='/'?'/index.html':p;}
async function copyOld(path){const keys=(await caches.keys()).filter(k=>k.startsWith('anlagenbuch-shell-')&&k!==CACHE).sort().reverse();for(const k of keys){const found=await(await caches.open(k)).match(path,{ignoreSearch:true});if(found)return found;}return null;}
async function cached(path){const hit=await(await caches.open(CACHE)).match(path,{ignoreSearch:true});return hit||await copyOld(path);}
async function store(path){const r=await fetch(new Request(path,{credentials:'same-origin',cache:'reload',redirect:'follow'}));if(!r.ok||r.redirected||r.type==='opaque')throw Error('Ungültige Offline-Datei: '+path);const ct=(r.headers.get('content-type')||'').toLowerCase();if(path.endsWith('.js')&&!/(javascript|ecmascript)/.test(ct))throw Error('JavaScript-Antwort falsch: '+path);if(path.endsWith('.html')&&!ct.includes('html'))throw Error('HTML-Antwort falsch: '+path);await(await caches.open(CACHE)).put(path,r.clone());return r;}
async function fill(paths){const missing=[];let pos=0;await Promise.all(Array.from({length:4},async()=>{while(pos<paths.length){const path=paths[pos++];try{await store(path);}catch(e){if(!await cached(path))missing.push(path);}}}));return missing;}
self.addEventListener('install',e=>e.waitUntil((async()=>{const missing=await fill(INSTALL_ASSETS);if(missing.length)throw Error('Offline-Paket nicht vollständig: '+missing.join(','));await self.skipWaiting();})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{await self.clients.claim();})()));
async function offlineStatic(req){
 const path=norm(req.url),hit=await cached(path);
 // Complete app shell is installed before activation. Cache-first prevents
 // accidental network-only responses when a connection is weak or unavailable.
 if(hit)return hit;
 try{
   const r=await fetch(req);
   if(r.ok&&!r.redirected&&r.type==='basic')await(await caches.open(CACHE)).put(path,r.clone()).catch(()=>{});
   return r;
 }catch(_){
   if(req.mode==='navigate')return await cached(path==='/app.html'?'/app.html':path==='/login.html'?'/login.html':'/index.html')||Response.error();
   return Response.error();
 }
}
async function media(req){const c=await caches.open(MEDIA_CACHE),hit=await c.match(req);if(hit)return hit;try{const r=await fetch(req);if(r.ok)await c.put(req,r.clone()).catch(()=>{});return r;}catch(_){return Response.error();}}
self.addEventListener('fetch',e=>{const req=e.request;if(req.method!=='GET')return;const u=new URL(req.url);if(u.origin!==self.location.origin)return;if(u.pathname==='/api/media'){e.respondWith(media(req));return;}if(u.pathname.startsWith('/api/')||u.pathname.startsWith('/server/')||u.pathname==='/companion-auth')return;const path=norm(req.url);if(req.mode==='navigate'||STATIC_PATHS.has(path)){e.respondWith(offlineStatic(req));}});
self.addEventListener('message',e=>{const msg=e.data||{};if(msg.type==='activate-now'){e.waitUntil(self.skipWaiting());return;}if(msg.type==='offline-check'){e.waitUntil((async()=>{const missing=[];for(const path of INSTALL_ASSETS){if(!await cached(path))missing.push(path);}e.source?.postMessage({type:'offline-check-result',version:VERSION,ready:missing.length===0,missing});})());}if(msg.type==='offline-warmup'){e.waitUntil((async()=>{const missing=await fill(INSTALL_ASSETS);e.source?.postMessage({type:'offline-warmup-result',version:VERSION,ready:missing.length===0,missing});})());}if(msg.type==='offline-media-prefetch'){e.waitUntil((async()=>{const c=await caches.open(MEDIA_CACHE);let ok=0,failed=0;for(const uri of [...new Set(Array.isArray(msg.uris)?msg.uris:[])].slice(0,2000)){if(typeof uri!=='string'||!/^(app-pdf|app-image|web-pdf|web-image):/.test(uri))continue;const url='/api/media?uri='+encodeURIComponent(uri);if(await c.match(url))continue;try{const r=await fetch(url,{credentials:'same-origin'});if(!r.ok)throw Error(String(r.status));await c.put(url,r.clone());ok++;}catch(_){failed++;}}e.source?.postMessage({type:'offline-media-result',downloaded:ok,failed});})());}});
