'use strict';
(function(){
const CODE39={
'0':'nnnwwnwnn','1':'wnnwnnnnw','2':'nnwwnnnnw','3':'wnwwnnnnn','4':'nnnwwnnnw','5':'wnnwwnnnn','6':'nnwwwnnnn','7':'nnnwnnwnw','8':'wnnwnnwnn','9':'nnwwnnwnn',
'A':'wnnnnwnnw','B':'nnwnnwnnw','C':'wnwnnwnnn','D':'nnnnwwnnw','E':'wnnnwwnnn','F':'nnwnwwnnn','G':'nnnnnwwnw','H':'wnnnnwwnn','I':'nnwnnwwnn','J':'nnnnwwwnn',
'K':'wnnnnnnww','L':'nnwnnnnww','M':'wnwnnnnwn','N':'nnnnwnnww','O':'wnnnwnnwn','P':'nnwnwnnwn','Q':'nnnnnnwww','R':'wnnnnnwwn','S':'nnwnnnwwn','T':'nnnnwnwwn',
'U':'wwnnnnnnw','V':'nwwnnnnnw','W':'wwwnnnnnn','X':'nwnnwnnnw','Y':'wwnnwnnnn','Z':'nwwnwnnnn','-':'nwnnnnwnw','.':'wwnnnnwnn',' ':'nwwnnnwnn','$':'nwnwnwnnn','/':'nwnwnnnwn','+':'nwnnnwnwn','%':'nnnwnwnwn','*':'nwnnwnwnn'};
function barcodeSvg(text){
 const value=String(text||'').toUpperCase().replace(/[^0-9A-Z. $/+%\-]/g,'');if(!value)return '';
 const full='*'+value+'*',narrow=2,wide=5,gap=2,quiet=18,h=76;let x=quiet,bars=[];
 for(const ch of full){const p=CODE39[ch];if(!p)continue;for(let i=0;i<9;i++){const w=p[i]==='w'?wide:narrow;if(i%2===0)bars.push(`<rect x="${x}" y="0" width="${w}" height="${h}"/>`);x+=w;}x+=gap;}
 const width=x+quiet;const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} 102" shape-rendering="crispEdges"><rect width="100%" height="100%" fill="white"/><g fill="black">${bars.join('')}</g><text x="${width/2}" y="96" text-anchor="middle" font-family="monospace" font-size="12">${value.replace(/&/g,'&amp;').replace(/</g,'&lt;')}</text></svg>`;
 return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);
}
function pumpDesignation(a,u){return ('V-VA-'+String(a.name||'').trim()+' '+String(u.name||'').trim()).trim();}
function unitQrValue(a,u){const stored=String(u&&u.barcode||'').trim();return stored||pumpDesignation(a,u);}
function unitQrPayload(a,u){return unitQrValue(a,u);}
function unitQrSvg(a,u){try{if(!window.QRRuntime)return '';const rows=QRRuntime.matrix(unitQrPayload(a,u)).split('\n'),n=rows.length,q=4,size=n+q*2,parts=[`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" shape-rendering="crispEdges"><rect width="100%" height="100%" fill="white"/>`];for(let y=0;y<n;y++)for(let x=0;x<n;x++)if(rows[y][x]==='1')parts.push(`<rect x="${x+q}" y="${y+q}" width="1" height="1" fill="black"/>`);parts.push('</svg>');return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(parts.join(''));}catch(_){return '';} }
function unitCard(u){return `<button class="unitCard" data-unit-open="${esc(u.id)}"><span><strong>${esc(u.name||'Einheit')}</strong><small>${u.pumpModel?esc(u.pumpModel):'Pumpenmodell nicht hinterlegt'}${u.serial?' · SN '+esc(u.serial):''}</small></span><span class="arrow">›</span></button>`;}
window.renderUnits=function(a){const box=$('unitsSection');if(!box)return;const rows=Array.isArray(a.units)?a.units:[];box.innerHTML=`<div class="row"><h2>Unit-Einheiten (${rows.length})</h2><button id="addUnit" class="light">+ Unit</button></div><p class="hint">Pumpen am Stellplatz ${esc(a.name)}. Jede Unit besitzt eigene Pumpendaten und einen Barcode.</p>${rows.length?rows.map(unitCard).join(''):'<div class="empty">Für diesen Stellplatz sind noch keine Units hinterlegt.</div>'}`;$('addUnit').onclick=()=>unitForm();};

const PSA_SIGNS=[
 {id:'WSM001',file:'psa/WSM001.jpg',label:'Rettungsweste benutzen'},
 {id:'M001',file:'psa/M001.jpg',label:'Allgemeines Gebotszeichen'},
 {id:'M003',file:'psa/M003.jpg',label:'Gehörschutz benutzen'},
 {id:'M004',file:'psa/M004.jpg',label:'Augenschutz benutzen'},
 {id:'M008',file:'psa/M008.jpg',label:'Fußschutz benutzen'},
 {id:'M009',file:'psa/M009.jpg',label:'Handschutz benutzen'},
 {id:'M010',file:'psa/M010.jpg',label:'Schutzkleidung benutzen'},
 {id:'M011',file:'psa/M011.jpg',label:'Hände waschen'},
 {id:'M012',file:'psa/M012.jpg',label:'Handlauf benutzen'},
 {id:'M013',file:'psa/M013.jpg',label:'Gesichtsschutz benutzen'},
 {id:'M014',file:'psa/M014.jpg',label:'Kopfschutz benutzen'},
 {id:'M015',file:'psa/M015.jpg',label:'Warnweste benutzen'},
 {id:'M017',file:'psa/M017.jpg',label:'Atemschutz benutzen'},
 {id:'M018',file:'psa/M018.jpg',label:'Auffanggurt benutzen'},
 {id:'M020',file:'psa/M020.jpg',label:'Rückhaltesystem benutzen'},
 {id:'M021',file:'psa/M021.jpg',label:'Vor Wartung/Reparatur freischalten'},
 {id:'M022',file:'psa/M022.jpg',label:'Hautschutzmittel benutzen'},
 {id:'M023',file:'psa/M023.jpg',label:'Übergang benutzen'},
 {id:'M024',file:'psa/M024.jpg',label:'Fußgängerweg benutzen'},
 {id:'M026',file:'psa/M026.jpg',label:'Schutzschürze benutzen'}
];
const PSA_IDS=new Set(PSA_SIGNS.map(x=>x.id));
function normalizePsaSigns(v){return [...new Set((Array.isArray(v)?v:[]).map(String).filter(x=>PSA_IDS.has(x)))];}
function psaEditHtml(u){const selected=new Set(normalizePsaSigns(u.psaSigns));return `<fieldset class="unitPsaFields"><legend>Schutzmaßnahmen / Persönliche PSA</legend><p class="hint">Wähle die für diese Unit vorgeschriebenen Schutzmaßnahmen. Mehrere Zeichen können gleichzeitig ausgewählt werden.</p><div class="psaPicker">${PSA_SIGNS.map(s=>`<label class="psaChoice ${selected.has(s.id)?'selected':''}" title="${esc(s.label)}"><input type="checkbox" name="psaSigns" value="${esc(s.id)}" ${selected.has(s.id)?'checked':''}><img src="${esc(s.file)}" alt="${esc(s.label)}"><span>${esc(s.label)}</span></label>`).join('')}</div></fieldset>`;}
function psaDisplayHtml(u){const ids=new Set(normalizePsaSigns(u.psaSigns)), rows=PSA_SIGNS.filter(s=>ids.has(s.id));return `<section class="unitPsaDisplay"><h3>Schutzmaßnahmen / Persönliche PSA</h3>${rows.length?`<div class="psaDisplayRow">${rows.map(s=>`<div class="psaDisplayItem" title="${esc(s.label)}"><img src="${esc(s.file)}" alt="${esc(s.label)}"><span>${esc(s.label)}</span></div>`).join('')}</div>`:'<p class="hint psaEmpty">Keine Schutzmaßnahmen ausgewählt.</p>'}</section>`;}


function hasAssetSettingValue(v){return v!==null&&v!==undefined&&String(v).trim()!=='';}
function formatAssetSettingValue(v,unit){if(!hasAssetSettingValue(v))return '';let t=typeof v==='number'?String(v).replace('.',','):String(v);return t+(unit?' '+unit:'');}
function getAssetValues(s){if(window.getAssetValueRows)return window.getAssetValueRows(s);s=(s&&typeof s==='object')?s:{};if(Object.prototype.hasOwnProperty.call(s,'assetValues'))return Array.isArray(s.assetValues)?s.assetValues:[];const out=[];if(hasAssetSettingValue(s.inlet))out.push({id:'legacy-inlet',label:'Stickstoff · Eingangsdruck',value:String(s.inlet).replace('.',','),unit:'bar'});return out;}
function assetSettingsCardsHtml(a){
 const s=a&&a.settings;if(!s||typeof s!=='object')return '';
 const cards=[];
 for(const v of getAssetValues(s)){if(!v||!String(v.label||'').trim()||!hasAssetSettingValue(v.value))continue;cards.push(`<div><small>${esc(String(v.label).toUpperCase())}</small><strong>${esc(formatAssetSettingValue(v.value,v.unit||''))}</strong></div>`);}
 for(const l of (Array.isArray(s.lines)?s.lines:[])){if(!l||!hasAssetSettingValue(l.value))continue;const label=String(l.name||'Leitung').trim()||'Leitung';cards.push(`<div><small>${esc(label.toUpperCase())}</small><strong>${esc(formatAssetSettingValue(l.value,l.unit||''))}</strong></div>`);}
 for(const h of (Array.isArray(s.heaters)?s.heaters:[])){if(!h||!hasAssetSettingValue(h.value))continue;const label='Heizung · '+(String(h.name||'Heizabschnitt').trim()||'Heizabschnitt');cards.push(`<div><small>${esc(label.toUpperCase())}</small><strong>${esc(formatAssetSettingValue(h.value,'°C'))}</strong></div>`);}
 const hint=String(s.hint||'').trim();
 return cards.join('')+(hint?`<div class="unitDetailWide"><small>HINWEIS</small><strong>${esc(hint)}</strong></div>`:'');
}
function combinedSettingsDetailHtml(a,u){
 const own=(Array.isArray(u&&u.customFields)?u.customFields:[]).filter(f=>f&&String(f.label||'').trim());
 const ownHtml=own.map(f=>`<div><small>${esc(String(f.label||'').toUpperCase())}</small><strong>${f.value?esc(f.value):'Nicht hinterlegt'}</strong></div>`).join('');
 const shared=assetSettingsCardsHtml(a);
 const content=ownHtml+shared;
 return `<div class="unitSettingsHeading unitCombinedHeading"><div class="row"><small>ANLAGEN-SOLLWERTE / EINSTELLUNGEN</small><button id="editCombinedSettings" class="light" type="button">Bearbeiten</button></div></div>${content||'<div class="unitDetailWide"><small>STATUS</small><strong>Noch keine Sollwerte oder Einstellungen hinterlegt.</strong></div>'}`;
}
function combinedAssetValueEditor(v){return `<div class="combinedAssetValueRow" data-asset-value-id="${esc(v.id||uid())}"><div><label>Bezeichnung</label><input class="assetValueLabel" value="${esc(v.label||'')}" maxlength="100" placeholder="z. B. Stickstoff · Eingangsdruck"></div><div><label>Wert</label><input class="assetValueValue" value="${esc(v.value===undefined||v.value===null?'':String(v.value))}" maxlength="200" placeholder="Nicht hinterlegt"></div><div><label>Einheit</label><input class="assetValueUnit" value="${esc(v.unit||'')}" maxlength="40" placeholder="z. B. bar"></div><button type="button" class="danger combinedAssetValueDelete">Feld löschen</button></div>`;}
function combinedLineEditor(l){return `<div class="combinedLineRow" data-line-id="${esc(l.id||uid())}"><div><label>Bezeichnung</label><input class="combinedLineName" value="${esc(l.name||'')}" maxlength="100" placeholder="z. B. N2 Dilution"></div><div><label>Sollwert</label><input class="combinedLineValue" value="${l.value===null||l.value===undefined?'':esc(String(l.value).replace('.',','))}" inputmode="decimal" placeholder="Nicht hinterlegt"></div><div><label>Einheit</label><input class="combinedLineUnit" value="${esc(l.unit||'')}" maxlength="40" placeholder="z. B. bar"></div><button type="button" class="danger combinedLineDelete">Feld löschen</button></div>`;}
function combinedHeaterEditor(h){return `<div class="combinedHeaterRow" data-heater-id="${esc(h.id||uid())}"><div><label>Bezeichnung</label><input class="combinedHeatName" value="${esc(h.name||'')}" maxlength="100" placeholder="Heizabschnitt"></div><div><label>Temperatur °C</label><input class="combinedHeatValue" value="${h.value===null||h.value===undefined?'':esc(String(h.value).replace('.',','))}" inputmode="decimal" placeholder="Nicht hinterlegt"></div><button type="button" class="danger combinedHeaterDelete">Feld löschen</button></div>`;}
function settingsCanonical(st){if(window.canonicalAssetSettings)return window.canonicalAssetSettings(st);return {assetValues:getAssetValues(st),lines:Array.isArray(st.lines)?st.lines:[],heaters:Array.isArray(st.heaters)?st.heaters:[],hint:String(st.hint||'')};}
function combinedSettingsForm(assetId,unitId){
 const a=state.assets.find(x=>x.id===assetId),u=ensureUnitData((a&&a.units||[]).find(x=>x.id===unitId));if(!a||!u)return;
 const st=(a.settings&&typeof a.settings==='object')?a.settings:{inlet:null,lines:[],heaters:[],hint:''};
 const last=(a.settingsHistory||[])[(a.settingsHistory||[]).length-1];
 const assetValues=getAssetValues(st),lines=(Array.isArray(st.lines)?st.lines:[]).map((x,i)=>({id:x.id||('line-'+i),name:x.name||'',value:x.value,unit:x.unit||''})),heaters=(Array.isArray(st.heaters)?st.heaters:[]);
 modal(`<h2>Anlagen-Sollwerte / Einstellungen bearbeiten</h2><p><strong>${esc(pumpDesignation(a,u))}</strong></p><p class="hint">Alles wird in der Unit-Ansicht in einem gemeinsamen Block angezeigt. Zusätzliche Werte dieser Unit gelten nur für diese Unit; Anlagenwerte gelten für alle Units dieser Anlage.</p><form id="combinedSettingsForm"><fieldset class="unitCustomFields"><legend>Zusätzliche Werte dieser Unit</legend><div id="combinedCustomRows">${(u.customFields||[]).map(f=>customFieldEditor(f)).join('')}</div><button type="button" id="combinedAddCustom" class="light">+ Feld hinzufügen</button></fieldset><fieldset><legend>Anlagenwerte</legend><p class="hint">Jeder Anlagenwert kann frei umbenannt, geändert, ergänzt oder gelöscht werden.</p><div id="combinedAssetValues">${assetValues.map(combinedAssetValueEditor).join('')}</div><button id="combinedAddAssetValue" type="button" class="light">+ Anlagenwert hinzufügen</button><div class="row settingEditorHeading"><h3>Leitungen / Medien</h3><button id="combinedAddLine" type="button" class="light">+ Feld hinzufügen</button></div><div id="combinedLines">${lines.map(combinedLineEditor).join('')}</div><div class="row settingEditorHeading"><h3>Rohrbegleitheizung</h3><button id="combinedAddHeater" type="button" class="light">+ Heizabschnitt</button></div><div id="combinedHeaters">${heaters.map(combinedHeaterEditor).join('')}</div><label for="combinedHint">Hinweis</label><textarea id="combinedHint" maxlength="10000">${esc(st.hint||'')}</textarea><label for="combinedAuthor">Geändert von (nur bei Anlagenwerten nötig)</label><input id="combinedAuthor" maxlength="100" value="${last?esc(last.author||''):''}" placeholder="Name"></fieldset><div class="actions"><button type="submit">Speichern</button><button id="cancel" type="button" class="light">Abbrechen</button></div></form>`);
 $('combinedAddCustom').onclick=()=>{$('combinedCustomRows').insertAdjacentHTML('beforeend',customFieldEditor({id:uid(),label:'',value:''}));};
 $('combinedCustomRows').onclick=e=>{const b=e.target.closest('.customDelete');if(b&&confirm('Dieses Feld löschen?'))b.closest('.unitCustomRow').remove();};
 $('combinedAddAssetValue').onclick=()=>{$('combinedAssetValues').insertAdjacentHTML('beforeend',combinedAssetValueEditor({id:uid(),label:'Neuer Anlagenwert',value:'',unit:''}));};
 $('combinedAssetValues').onclick=e=>{const b=e.target.closest('.combinedAssetValueDelete');if(b&&confirm('Diesen Anlagenwert löschen?'))b.closest('.combinedAssetValueRow').remove();};
 $('combinedAddLine').onclick=()=>{$('combinedLines').insertAdjacentHTML('beforeend',combinedLineEditor({id:uid(),name:'Neues Feld',value:null,unit:''}));};
 $('combinedLines').onclick=e=>{const b=e.target.closest('.combinedLineDelete');if(b&&confirm('Dieses Anlagenfeld löschen?'))b.closest('.combinedLineRow').remove();};
 $('combinedAddHeater').onclick=()=>{$('combinedHeaters').insertAdjacentHTML('beforeend',combinedHeaterEditor({id:uid(),name:'Heizabschnitt',value:null}));};
 $('combinedHeaters').onclick=e=>{const b=e.target.closest('.combinedHeaterDelete');if(b&&confirm('Diesen Heizabschnitt löschen?'))b.closest('.combinedHeaterRow').remove();};
 $('combinedSettingsForm').onsubmit=e=>{e.preventDefault();try{
   const custom=[...document.querySelectorAll('#combinedCustomRows .unitCustomRow')].map(el=>({id:el.dataset.customId||uid(),label:el.querySelector('.customLabel').value.trim(),value:el.querySelector('.customValue').value.trim()})).filter(x=>x.label);
   const assetVals=[...document.querySelectorAll('#combinedAssetValues .combinedAssetValueRow')].map(el=>({id:el.dataset.assetValueId||uid(),label:el.querySelector('.assetValueLabel').value.trim(),value:el.querySelector('.assetValueValue').value.trim(),unit:el.querySelector('.assetValueUnit').value.trim()})).filter(x=>x.label);
   const lineRows=[...document.querySelectorAll('.combinedLineRow')].map(el=>({id:el.dataset.lineId||uid(),name:el.querySelector('.combinedLineName').value.trim(),value:C.decimal(el.querySelector('.combinedLineValue').value),unit:el.querySelector('.combinedLineUnit').value.trim()})).filter(x=>x.name||x.value!==null);
   const heaterRows=[...document.querySelectorAll('.combinedHeaterRow')].map(el=>({id:el.dataset.heaterId||uid(),name:el.querySelector('.combinedHeatName').value.trim(),value:C.decimal(el.querySelector('.combinedHeatValue').value,true)})).filter(x=>x.name||x.value!==null);
   const nextCanon={assetValues:assetVals,lines:lineRows,heaters:heaterRows,hint:$('combinedHint').value.trim()};
   const nextSettings={...st,inlet:null,assetValues:assetVals,lines:lineRows,heaters:heaterRows,hint:nextCanon.hint};
   const assetChanged=JSON.stringify(nextCanon)!==JSON.stringify(settingsCanonical(st)),customChanged=JSON.stringify(custom)!==JSON.stringify(u.customFields||[]),author=$('combinedAuthor').value.trim();
   if(assetChanged&&!author)throw Error('Bitte bei geänderten Anlagenwerten Name eintragen.');
   if(!assetChanged&&!customChanged){$('modal').close();toast('Keine Änderungen.');return;}
   if(change(next=>{const aa=next.assets.find(x=>x.id===assetId),uu=(aa.units||[]).find(x=>x.id===unitId);uu.customFields=custom;if(assetChanged){aa.settings=nextSettings;aa.settingsHistory=Array.isArray(aa.settingsHistory)?aa.settingsHistory:[];aa.settingsHistory.push({id:uid(),at:new Date().toISOString(),author,values:C.clone(nextSettings)});}})){$('modal').close();unitDetail(unitId);toast('Anlagen-Sollwerte / Einstellungen gespeichert.');}
 }catch(err){toast(err.message||String(err));}};
}
const UNIT_STD_DEFAULTS={name:'Unit-Einheit',pumpModel:'Pumpen Modell',type:'Typ',special:'Special',serial:'Serien-Nummer',barcode:'Barcode'};
const UNIT_STD_KEYS=['name','pumpModel','type','special','serial','barcode'];
function ensureFieldConfig(u){
 u.fieldConfig=(u.fieldConfig&&typeof u.fieldConfig==='object'&&!Array.isArray(u.fieldConfig))?u.fieldConfig:{};
 for(const k of UNIT_STD_KEYS){const d=UNIT_STD_DEFAULTS[k],x=u.fieldConfig[k];u.fieldConfig[k]={label:String(x&&x.label||d).trim().slice(0,100)||d,visible:(k==='name'||k==='serial')?true:(x&&x.visible===false?false:true)};}
 return u.fieldConfig;
}
function stdLabel(u,k){return (ensureFieldConfig(u)[k]||{}).label||UNIT_STD_DEFAULTS[k];}
function stdVisible(u,k){return k==='name'||k==='serial'||(ensureFieldConfig(u)[k]||{}).visible!==false;}
function stdFieldEditor(u,k){const cfg=ensureFieldConfig(u)[k],required=k==='name'?' required':'',max=k==='barcode'?300:(k==='name'?100:200);return `<div class="unitStdRow" data-std-key="${esc(k)}"><div><label>Feldbezeichnung</label><input class="stdLabel" value="${esc(cfg.label)}" maxlength="100" required></div><div><label>Wert</label><input class="stdValue" value="${esc(u[k]||'')}" maxlength="${max}"${required}></div>${k==='name'?'<span class="stdLocked">Hauptfeld</span>':k==='serial'?'<span class="stdLocked">immer sichtbar</span>':'<button type="button" class="danger stdDelete">Feld löschen</button>'}</div>`;}
function hiddenStdButtons(u){return UNIT_STD_KEYS.filter(k=>k!=='name'&&!stdVisible(u,k)).map(k=>`<button type="button" class="light stdRestore" data-std-restore="${esc(k)}">+ ${esc(stdLabel(u,k))} wieder hinzufügen</button>`).join('');}
function customFieldEditor(f){return `<div class="unitCustomRow" data-custom-id="${esc(f.id||uid())}"><div><label>Feldbezeichnung</label><input class="customLabel" aria-label="Feldbezeichnung" placeholder="z. B. IP-Adresse" value="${esc(f.label||'')}" maxlength="100"></div><div><label>Wert</label><input class="customValue" aria-label="Wert" placeholder="Wert" value="${esc(f.value||'')}" maxlength="1000"></div><button type="button" class="danger customDelete">Feld löschen</button></div>`;}
function deleteUnitEverywhere(assetId,unitId){
 if(!confirm('Diese Unit wirklich löschen?'))return false;
 const ok=change(st=>{const a=st.assets.find(x=>x.id===assetId);if(!a)return;a.units=(a.units||[]).filter(x=>x.id!==unitId);if(Array.isArray(st.dailyBusiness))st.dailyBusiness=st.dailyBusiness.filter(x=>!(x&&x.assetId===assetId&&x.unitId===unitId));});
 if(ok){$('modal').close();showDetail(assetId,false);toast('Unit gelöscht und für die Synchronisierung vorgemerkt.');if(window.updateTodayButton)window.updateTodayButton();}
 return ok;
}
function unitForm(id){const a=state.assets.find(x=>x.id===selected),u=ensureUnitData((a.units||[]).find(x=>x.id===id)||{id:id||uid(),name:'',pumpModel:'',type:'',special:'',serial:'',barcode:'',fieldConfig:{},customFields:[],settingsText:'',parts:[],hours:[],handlingInstruction:{libraryId:'',text:'',pdfName:'',pdfUri:''},notes:[],psaSigns:['M009','M017'],psaDefaultSeedVersion:1,serialSeedVersion:4,serialManual:false});
 modal(`<h2>${id?'Unit bearbeiten':'Unit hinzufügen'}</h2><p><strong>Tool ID:</strong> ${esc(a.name)}</p><form id="unitForm"><fieldset class="unitStdFields"><legend>Bestehende Unit-Felder</legend><p class="hint">Die Feldnamen kannst du frei ändern. Pumpenmodell, Typ, Special und Barcode können gelöscht und später wieder hinzugefügt werden. Die Seriennummer bleibt bei jeder Unit immer sichtbar, kann aber jederzeit geändert werden. Das Hauptfeld für die Unit bleibt technisch erhalten, kann aber ebenfalls umbenannt werden.</p><div id="unitStdRows">${UNIT_STD_KEYS.filter(k=>stdVisible(u,k)).map(k=>stdFieldEditor(u,k)).join('')}</div><div id="unitStdRestore" class="actions">${hiddenStdButtons(u)}</div></fieldset>${psaEditHtml(u)}<div class="actions"><button>Speichern</button><button id="cancel" type="button" class="light">Abbrechen</button>${id?'<button id="deleteUnit" type="button" class="danger">Unit löschen</button>':''}</div></form>`);
 const deleted=new Set(UNIT_STD_KEYS.filter(k=>!stdVisible(u,k)));
 const restoreBox=$('unitStdRestore');
 function repaintRestore(){restoreBox.innerHTML=[...deleted].map(k=>`<button type="button" class="light stdRestore" data-std-restore="${esc(k)}">+ ${esc(stdLabel(u,k))} wieder hinzufügen</button>`).join('');}
 $('unitStdRows').onclick=e=>{const b=e.target.closest('.stdDelete');if(!b)return;const row=b.closest('.unitStdRow'),k=row.dataset.stdKey;if(confirm(`Feld „${row.querySelector('.stdLabel').value.trim()||UNIT_STD_DEFAULTS[k]}“ wirklich löschen? Der aktuelle Wert wird entfernt.`)){deleted.add(k);row.remove();repaintRestore();}};
 restoreBox.onclick=e=>{const b=e.target.closest('.stdRestore');if(!b)return;const k=b.dataset.stdRestore;deleted.delete(k);$('unitStdRows').insertAdjacentHTML('beforeend',stdFieldEditor(u,k));repaintRestore();};
 $('unitForm').onsubmit=e=>{e.preventDefault();const val={id:u.id,name:u.name||'',pumpModel:u.pumpModel||'',type:u.type||'',special:u.special||'',serial:u.serial||'',barcode:u.barcode||'',fieldConfig:{},customFields:C.clone(u.customFields||[]),settingsText:u.settingsText||'',parts:u.parts||[],hours:u.hours||[],handlingInstruction:u.handlingInstruction||{libraryId:'',text:'',pdfName:'',pdfUri:''},notes:u.notes||[],psaSigns:[...document.querySelectorAll('input[name="psaSigns"]:checked')].map(x=>x.value),psaDefaultSeedVersion:Number(u.psaDefaultSeedVersion||1),serialSeedVersion:Number(u.serialSeedVersion||4),serialManual:u.serialManual===true};
  for(const k of UNIT_STD_KEYS){const row=document.querySelector(`.unitStdRow[data-std-key="${k}"]`),old=ensureFieldConfig(u)[k];if(row){val[k]=row.querySelector('.stdValue').value.trim();val.fieldConfig[k]={label:row.querySelector('.stdLabel').value.trim()||UNIT_STD_DEFAULTS[k],visible:true};}else{val[k]=k==='name'?(u.name||''):'';val.fieldConfig[k]={label:(old&&old.label)||UNIT_STD_DEFAULTS[k],visible:k==='name'};}}
  if(String(val.serial||'')!==String(u.serial||'')){val.serialManual=true;val.serialSeedVersion=4;}
  if(!val.name)return toast('Das technische Unit-Hauptfeld benötigt einen Wert.');
  const oldName=String(u.name||'').trim(),oldBarcode=String(u.barcode||'').trim(),newBarcode=String(val.barcode||'').trim(),oldAuto=pumpDesignation(a,{name:oldName}),newAuto=pumpDesignation(a,{name:val.name});
  if(!newBarcode)val.barcode=newAuto;
  else if(val.name!==oldName&&newBarcode===oldBarcode&&(!oldBarcode||oldBarcode===oldAuto))val.barcode=newAuto;
  if(change(s=>{const units=s.assets.find(x=>x.id===selected).units,i=units.findIndex(x=>x.id===val.id);if(i<0)units.push(val);else units[i]=val;})){$('modal').close();showDetail(selected,false);toast('Unit gespeichert und für die Synchronisierung vorgemerkt.');}};
 if(id)$('deleteUnit').onclick=()=>deleteUnitEverywhere(selected,id);
}
function isExcelKuerzelField(f){const label=String(f&&f.label||'').trim().toUpperCase().replace(/Ü/g,'U').replace(/UE/g,'U');return label==='KURZEL';}
function ensureUnitData(u){u.fieldConfig=(u.fieldConfig&&typeof u.fieldConfig==='object'&&!Array.isArray(u.fieldConfig))?u.fieldConfig:{};ensureFieldConfig(u);u.customFields=(Array.isArray(u.customFields)?u.customFields:[]).filter(f=>!isExcelKuerzelField(f));u.settingsText=u.settingsText||'';u.parts=Array.isArray(u.parts)?u.parts:[];u.hours=Array.isArray(u.hours)?u.hours:[];u.handlingInstruction=u.handlingInstruction||{libraryId:'',text:'',pdfName:'',pdfUri:''};u.notes=Array.isArray(u.notes)?u.notes:[];u.psaSigns=normalizePsaSigns(u.psaSigns);return u;}
function unitDetail(id){const a=state.assets.find(x=>x.id===selected),u0=(a.units||[]).find(x=>x.id===id);if(!u0)return;const u=ensureUnitData(u0),bc=barcodeSvg(u.barcode),qrValue=unitQrValue(a,u),qr=unitQrSvg(a,u),designation=pumpDesignation(a,u),shared=(state.instructionLibrary||[]).find(x=>x&&!x.attachmentOnly&&x.id===u.handlingInstruction.libraryId),sharedPdfs=shared?(shared.pdfRefs||[]).map(pid=>(state.instructionLibrary||[]).find(x=>x&&x.attachmentOnly&&x.id===pid)).filter(Boolean):[],hours=[...u.hours].sort((x,y)=>String(y.date).localeCompare(String(x.date))),last=hours[0];modal(`<h2>${esc(designation)}</h2><p class="hint">Tool ID ${esc(a.name)} · ${esc(a.module)} · Koordinate Y ${esc(a.y)} / X ${esc(a.x)}</p><div class="actions unitTopActions"><button id="unitToday">Für Tagesgeschäft vormerken</button></div>${psaDisplayHtml(u)}<section class="equipmentBox unitWorkTop"><div class="row"><h2>Notiz und Arbeiten (${u.notes.length})</h2><button id="unitWork" class="light">+ Arbeit</button></div>${u.notes.length?[...u.notes].reverse().map(n=>`<article class="record"><strong>${esc(n.date)}</strong><p>${esc(n.text)}</p><p class="hint">${esc(n.technicians||'')}</p></article>`).join(''):'<p class="empty">Noch keine Arbeiten eingetragen.</p>'}</section><div class="unitDetails">${['name','pumpModel','type','serial','special'].filter(k=>stdVisible(u,k)).map(k=>`<div><small>${esc(String(stdLabel(u,k)).toUpperCase())}</small><strong>${u[k]?esc(u[k]):'Nicht hinterlegt'}</strong></div>`).join('')}${combinedSettingsDetailHtml(a,u)}</div>
<section class="equipmentBox"><div class="row"><h2>Ersatzteile (${u.parts.length})</h2><button id="unitPart" class="light">+ Teil</button></div>${u.parts.length?u.parts.map(p=>`<article class="record"><strong>${esc(p.name)}</strong><p class="hint">${p.number?esc(p.number):'ohne Teilenummer'} · Menge ${esc(String(p.quantity||1))}</p></article>`).join(''):'<p class="empty">Noch keine Ersatzteile hinterlegt.</p>'}</section>
<section class="equipmentBox"><div class="row"><h2>Betriebsstunden</h2><button id="unitHours" class="light">+ Ablesung</button></div><p>${last?`<strong>${esc(String(last.value))} h</strong> · ${esc(last.date)}`:'Noch keine Ablesung hinterlegt.'}</p></section>
<section class="equipmentBox"><div class="row"><h2>Hantierungsanweisung</h2><button id="unitInstruction" class="light">${shared?'Zuweisung ändern':'Aus Pool zuweisen'}</button></div>${shared?`<article class="record"><strong>${esc(shared.title)}</strong>${shared.text?`<p>${esc(shared.text)}</p>`:''}${sharedPdfs.length?sharedPdfs.map(p=>`<p>${esc(p.title||p.pdfName||'PDF')} <button data-mpdf-open="${esc(p.id)}">Öffnen</button></p>`).join(''):'<p class="hint">Keine PDF hinterlegt.</p>'}<button id="unitInstructionRemove" class="danger">Zuweisung entfernen</button></article>`:'<p class="empty">Noch keine Hantierungsanweisung aus dem zentralen Pool zugeordnet.</p>'}<div class="row"><strong>Anlagenspezifische Ergänzung</strong><button id="unitHandlingText" class="light">Bearbeiten</button></div>${u.handlingInstruction.text?`<p>${esc(u.handlingInstruction.text)}</p>`:'<p class="empty">Keine Ergänzung.</p>'}</section>
${qr?`<div class="barcodeBox pumpQrBox"><strong>Unit-QR-Code</strong><img src="${qr}" alt="QR-Code ${esc(qrValue)}"><p><strong>${esc(qrValue)}</strong></p></div>`:''}${stdVisible(u,'barcode')&&bc?`<details><summary>Maschinen-Barcode anzeigen</summary><div class="barcodeBox"><img src="${bc}" alt="Barcode ${esc(u.barcode)}"><p>${esc(u.barcode)}</p></div></details>`:''}<div class="actions"><button id="unitFault" class="danger">⚠ Störung melden</button><button id="editUnit">Unit bearbeiten</button><button id="deleteUnitDetail" class="danger">Unit löschen</button><button id="cancel" class="light">Schließen</button></div>`);
$('editUnit').onclick=()=>unitForm(id);if($('deleteUnitDetail'))$('deleteUnitDetail').onclick=()=>deleteUnitEverywhere(a.id,u.id);if($('editCombinedSettings'))$('editCombinedSettings').onclick=()=>combinedSettingsForm(a.id,u.id);$('unitFault').onclick=()=>window.reportUnitFault&&window.reportUnitFault(a.id,u.id);$('unitToday').onclick=()=>addToToday(a.id,u.id);
$('unitHandlingText').onclick=()=>unitHandlingForm(a.id,u.id);$('unitPart').onclick=()=>unitPartForm(a.id,u.id);$('unitHours').onclick=()=>unitHoursForm(a.id,u.id);$('unitWork').onclick=()=>unitWorkForm(a.id,u.id,false);$('unitInstruction').onclick=()=>unitInstructionPicker(a.id,u.id);if($('unitInstructionRemove'))$('unitInstructionRemove').onclick=()=>{if(mutateUnit(a.id,u.id,x=>{x.handlingInstruction.libraryId='';x.handlingInstruction.updatedAt=Date.now();})){unitDetail(u.id);toast('Hantierungsanweisung von dieser Unit entfernt.');if(window.handlingSyncCommit)window.handlingSyncCommit(false);}};
}
function mutateUnit(assetId,unitId,fn){return change(st=>{const a=st.assets.find(x=>x.id===assetId),u=(a.units||[]).find(x=>x.id===unitId);ensureUnitData(u);fn(u,a);});}
function unitTextForm(aid,uid0,key,title,label){const a=state.assets.find(x=>x.id===aid),u=ensureUnitData((a.units||[]).find(x=>x.id===uid0));modal(`<h2>${esc(title)}</h2><form id="ux"><label>${esc(label)}</label><textarea name="v" maxlength="50000">${esc(u[key]||'')}</textarea><div class="actions"><button>Speichern</button><button id="cancel" type="button" class="light">Abbrechen</button></div></form>`);$('ux').onsubmit=e=>{e.preventDefault();if(mutateUnit(aid,uid0,x=>x[key]=e.target.elements.v.value.trim()))unitDetail(uid0);};}
function unitHandlingForm(aid,uid0){const a=state.assets.find(x=>x.id===aid),u=ensureUnitData((a.units||[]).find(x=>x.id===uid0));modal(`<h2>Anlagenspezifische Ergänzung</h2><form id="ux"><textarea name="v" maxlength="50000">${esc(u.handlingInstruction.text||'')}</textarea><div class="actions"><button>Speichern</button><button id="cancel" type="button" class="light">Abbrechen</button></div></form>`);$('ux').onsubmit=e=>{e.preventDefault();if(mutateUnit(aid,uid0,x=>x.handlingInstruction.text=e.target.elements.v.value.trim()))unitDetail(uid0);};}
function unitPartForm(aid,uid0){modal(`<h2>Ersatzteil hinzufügen</h2><form id="ux"><label>Bezeichnung</label><input name="name" required><label>Teilenummer</label><input name="number"><label>Menge</label><input name="quantity" value="1" inputmode="decimal"><div class="actions"><button>Speichern</button><button id="cancel" type="button" class="light">Abbrechen</button></div></form>`);$('ux').onsubmit=e=>{e.preventDefault();const f=e.target.elements;if(mutateUnit(aid,uid0,u=>u.parts.push({id:Date.now().toString(36),name:f.name.value.trim(),number:f.number.value.trim(),quantity:f.quantity.value.trim()||'1'})))unitDetail(uid0);};}
function unitHoursForm(aid,uid0){modal(`<h2>Betriebsstunden eintragen</h2><form id="ux"><label>Datum</label><input type="date" name="date" value="${new Date().toISOString().slice(0,10)}" required><label>Zählerstand in Stunden</label><input name="value" inputmode="decimal" required><div class="actions"><button>Speichern</button><button id="cancel" type="button" class="light">Abbrechen</button></div></form>`);$('ux').onsubmit=e=>{e.preventDefault();const f=e.target.elements;if(mutateUnit(aid,uid0,u=>u.hours.push({id:Date.now().toString(36),date:f.date.value,value:f.value.value.trim()})))unitDetail(uid0);};}
function unitInstructionPicker(aid,uid0){const u=ensureUnitData((state.assets.find(x=>x.id===aid)?.units||[]).find(x=>x.id===uid0)||{}),rows=(state.instructionLibrary||[]).filter(i=>i&&!i.attachmentOnly);modal(`<h2>Hantierungsanweisung zuweisen</h2><p class="hint">Zentraler Pool – die Auswahl wird direkt dieser einzelnen Unit zugeordnet und funktioniert auch offline.</p>${rows.length?rows.map(i=>`<article class="record"><strong>${esc(i.title)}</strong><p class="hint">${esc(i.pumpModel||'')}${(i.pdfRefs||[]).length?` · ${(i.pdfRefs||[]).length} PDF${(i.pdfRefs||[]).length===1?'':'s'}`:''}</p><button data-uinst="${esc(i.id)}" ${u.handlingInstruction.libraryId===i.id?'disabled':''}>${u.handlingInstruction.libraryId===i.id?'Bereits zugeordnet':'Dieser Unit zuordnen'}</button></article>`).join(''):'<p class="empty">Im Pool sind noch keine Anweisungen vorhanden.</p>'}<button id="cancel" class="light">Schließen</button>`);document.querySelectorAll('[data-uinst]').forEach(b=>b.onclick=()=>{if(mutateUnit(aid,uid0,x=>{x.handlingInstruction.libraryId=b.dataset.uinst;x.handlingInstruction.updatedAt=Date.now();})){unitDetail(uid0);toast('Hantierungsanweisung dieser Unit zugeordnet.');if(window.handlingSyncCommit)window.handlingSyncCommit(false);}});}
function unitWorkForm(aid,uid0,finishToday){const a=state.assets.find(x=>x.id===aid),u=ensureUnitData((a.units||[]).find(x=>x.id===uid0));modal(`<h2>Arbeit dokumentieren</h2><p><strong>${esc(pumpDesignation(a,u))}</strong></p><form id="ux"><label>Datum</label><input type="date" name="date" value="${new Date().toISOString().slice(0,10)}" required><label>Monteure</label><input name="technicians" required><label>Durchgeführte Arbeit</label><textarea name="text" required maxlength="10000"></textarea><div class="actions"><button>Speichern${finishToday?' + erledigen':''}</button><button id="cancel" type="button" class="light">Abbrechen</button></div></form>`);$('ux').onsubmit=e=>{e.preventDefault();const f=e.target.elements,n={id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),date:f.date.value,workType:'turnus',technicians:f.technicians.value.trim(),text:f.text.value.trim(),unitId:u.id,unitName:u.name};if(!n.technicians||!n.text)return;change(st=>{const aa=st.assets.find(x=>x.id===aid),uu=ensureUnitData((aa.units||[]).find(x=>x.id===uid0));uu.notes.push(n);aa.notes=aa.notes||[];aa.notes.push(n);});if(finishToday){const rows=todayRows(),r=rows.find(x=>x.assetId===aid&&x.unitId===uid0);if(r)r.done=true;saveToday(rows);}unitDetail(uid0);if(window.updateTodayButton)window.updateTodayButton();};}
window.addUnitToToday=addToToday;
function unitNorm(v){return String(v||'').trim().toUpperCase().replace(/^V-VA-\s*/,'').replace(/[^A-Z0-9]+/g,'');}
function scannedUnitCandidates(raw){const key=unitNorm(raw),map=new Map();if(!key)return[];const richness=u=>[u.pumpModel,u.type,u.special,u.serial,u.barcode,...((u.customFields||[]).map(f=>f.value))].filter(Boolean).length;for(const a of state.assets||[])for(const u0 of a.units||[]){const u=ensureUnitData(u0),keys=[pumpDesignation(a,u),`${a.name} ${u.name}`,u.barcode,u.name,...(u.customFields||[]).map(f=>f.value)];if(keys.some(x=>unitNorm(x)===key)){const k=a.id+'|'+unitNorm(u.name),prev=map.get(k);if(!prev||richness(u)>richness(prev.u))map.set(k,{a,u});}}return[...map.values()];}
window.openScannedText=function(raw){raw=String(raw||'').trim();if(!raw)return false;try{const url=new URL(raw);if(url.protocol==='de.modulbuch.anlagen:'){const aid=url.searchParams.get('asset'),uid0=url.searchParams.get('unit');if(aid&&uid0){const a=state.assets.find(x=>x.id===aid),u=a&&(a.units||[]).find(x=>x.id===uid0);if(a&&u){if($('modal').open)$('modal').close();window.openUnitAt(aid,uid0);toast('Unit-QR erkannt: '+pumpDesignation(a,u));return true;}}if(aid){const a=state.assets.find(x=>x.id===aid);if(a){if($('modal').open)$('modal').close();showDetail(aid);toast('QR-Code erkannt: '+a.name);return true;}}}}catch(_){}
 const direct=state.assets.find(a=>a.id===raw||unitNorm(a.name)===unitNorm(raw));const rows=scannedUnitCandidates(raw);if(rows.length===1){if($('modal').open)$('modal').close();window.openUnitAt(rows[0].a.id,rows[0].u.id);toast('Text-QR erkannt: '+pumpDesignation(rows[0].a,rows[0].u));return true;}if(rows.length>1){modal(`<h2>QR-Code zuordnen</h2><p>Der Text passt zu mehreren Units. Bitte die richtige auswählen.</p>${rows.map(r=>`<button class=\"unitCard\" data-qr-unit=\"${esc(r.a.id)}|${esc(r.u.id)}\"><span><strong>${esc(pumpDesignation(r.a,r.u))}</strong><small>${esc(r.a.module)} · Y ${esc(r.a.y)} / X ${esc(r.a.x)}</small></span><span class=\"arrow\">›</span></button>`).join('')}<button id=\"cancel\" class=\"light\">Abbrechen</button>`);document.querySelectorAll('[data-qr-unit]').forEach(b=>b.onclick=()=>{const [a,u]=b.dataset.qrUnit.split('|');$('modal').close();window.openUnitAt(a,u);});return true;}if(direct){if($('modal').open)$('modal').close();showDetail(direct.id);toast('Text-QR erkannt: '+direct.name);return true;}return false;};
window.openUnitById=unitDetail;
function todayDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function todayRows(){
 const date=todayDate();
 // Ab 1.71 liegt das Tagesgeschäft im zentral gespeicherten App-Zustand.
 // Einmalig vorhandene 1.70-Einträge aus localStorage übernehmen.
 let rows=Array.isArray(state&&state.dailyBusiness)?state.dailyBusiness.filter(r=>r&&(r.date===date||(!r.done&&r.date<date))):[];
 if(!rows.length){try{const old=JSON.parse(localStorage.getItem('anlagenbuch-tagesliste-'+date)||'[]');if(Array.isArray(old)&&old.length){rows=old.map(r=>({...r,date}));const s=C.clone(state);s.dailyBusiness=(Array.isArray(s.dailyBusiness)?s.dailyBusiness:[]).filter(r=>r&&r.date!==date).concat(rows);persist(s);localStorage.removeItem('anlagenbuch-tagesliste-'+date);}}catch(_){}}
 return rows;
}
window.getTodayRows=todayRows;
window.getTodayOpenCount=()=>todayRows().filter(r=>!r.done).length;
function saveToday(rows){
 const date=todayDate(),s=C.clone(state);s.dailyBusiness=(Array.isArray(s.dailyBusiness)?s.dailyBusiness:[]).filter(r=>r&&r.date!==date&&(r.done||!(r.date<date))).concat(rows.map(r=>({...r,id:r.id||('today-'+(r.date||date)+'-'+r.assetId+'-'+r.unitId),date:r.date||date})));
 if(!persist(s))return false;
 try{localStorage.removeItem('anlagenbuch-tagesliste-'+date);}catch(_){}
 return true;
}
function addToToday(assetId,unitId){
 const rows=todayRows();
 if(!rows.some(r=>r.assetId===assetId&&r.unitId===unitId&&!r.done)){
   const old=rows.find(r=>r.assetId===assetId&&r.unitId===unitId);
   if(old)old.done=false;else rows.push({id:'today-'+todayDate()+'-'+assetId+'-'+unitId,assetId,unitId,date:todayDate(),done:false});
   if(saveToday(rows)){toast('Pumpe für Arbeiten Heute – Tagesgeschäft vorgemerkt.');render();if(window.updateTodayButton)window.updateTodayButton();if(window.publishWidget)window.publishWidget();}
 }else toast('Pumpe ist für heute bereits vorgemerkt.');
}
window.openTodayList=function(){const rows=todayRows().filter(r=>!r.done),valid=rows.map(r=>{const a=state.assets.find(x=>x.id===r.assetId),u=a&&(a.units||[]).find(x=>x.id===r.unitId);return a&&u?{...r,a,u}:null;}).filter(Boolean);modal(`<h2>Arbeiten Heute – Tagesgeschäft</h2><p class="hint">Alle offenen Arbeiten, auch aus vergangenen Tagen. Sie bleiben bis zum Erledigen oder Entfernen sichtbar.</p>${valid.length?valid.map(r=>`<article class="record"><div class="row"><strong>${esc(pumpDesignation(r.a,r.u))}</strong></div><p class="hint">${r.date<todayDate()?'Offen seit '+esc(r.date)+' · ':''}${esc(r.a.module)} · Tool ID ${esc(r.a.name)} · Y ${esc(r.a.y)} / X ${esc(r.a.x)}</p><div class="actions"><button data-today-open="${esc(r.assetId)}|${esc(r.unitId)}">Pumpe öffnen</button><button data-today-done="${esc(r.assetId)}|${esc(r.unitId)}" class="light">Als erledigt markieren</button><button data-today-remove="${esc(r.assetId)}|${esc(r.unitId)}" class="danger">Entfernen</button></div></article>`).join(''):'<div class="empty">Für heute sind noch keine Pumpen hinterlegt.</div>'}<div class="actions"><button id="cancel" class="light">Schließen</button></div>`);};
window.updateTodayButton=function(){const rows=todayRows().filter(r=>!r.done),b=document.getElementById('todayPumps');if(b){b.textContent=`Arbeiten Heute – Tagesgeschäft (${rows.length})`;b.classList.toggle('todayActive',rows.length>0);}try{if(window.WidgetBridge&&state){const faults=[];for(const a of state.assets||[])for(const f of a.faults||[])if(f.status!=='resolved')faults.push({id:f.id,status:f.status,asset:a.name,at:Date.parse(f.updatedAt)||0});WidgetBridge.update(JSON.stringify({faults,todayCount:rows.length}));}}catch(_){}if(window.updateHeaderSummary)window.updateHeaderSummary(); };
document.addEventListener('click',e=>{let b=e.target.closest('[data-today-open]');if(b){const [a,u]=b.dataset.todayOpen.split('|');$('modal').close();window.openUnitAt&&window.openUnitAt(a,u);return;}b=e.target.closest('[data-today-done]');if(b){const [a,u]=b.dataset.todayDone.split('|'),rows=todayRows(),r=rows.find(x=>x.assetId===a&&x.unitId===u);if(r&&!r.done){unitWorkForm(a,u,true);}return;}b=e.target.closest('[data-today-remove]');if(b){const [a,u]=b.dataset.todayRemove.split('|');if(saveToday(todayRows().filter(x=>!(x.assetId===a&&x.unitId===u)))){openTodayList();render();if(window.updateTodayButton)window.updateTodayButton();}return;}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-unit-open]');if(b)unitDetail(b.dataset.unitOpen);});
})();
