import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const browser=await chromium.launch({headless:true,channel:'msedge'}),errors=[];
const tag=Date.now().toString().slice(-5);
async function device(){const context=await browser.newContext();const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:8788');await page.locator('#password').fill('test-busch');await page.locator('button[type=submit]').click();await page.waitForFunction(()=>window.OneDriveSync&&window.state!==null&&document.getElementById('webLoading').hidden);await page.evaluate(()=>OneDriveSync.sync());return {context,page};}
async function edit(p,field,value){return p.evaluate(({field,value})=>{const s=JSON.parse(Native.load());s.assets[0][field]=value;if(!Native.save(JSON.stringify(s)))throw Error('save failed');}, {field,value});}
async function sync(p){await p.evaluate(()=>OneDriveSync.sync());await p.waitForFunction(()=>!OneDriveSync.status().busy);}
try{
 const a=await device(),b=await device();await a.context.setOffline(true);await b.context.setOffline(true);
 await edit(a.page,'y','offline-A'+tag);await edit(b.page,'x','offline-B'+tag);
 await a.page.reload();await a.page.waitForFunction(()=>window.OneDriveSync&&document.getElementById('webLoading').hidden);assert.equal(await a.page.evaluate(()=>JSON.parse(Native.load()).assets[0].y),'offline-A'+tag);
 await a.context.setOffline(false);await sync(a.page);await b.context.setOffline(false);await sync(b.page);await sync(a.page);
 assert.equal(await a.page.evaluate(()=>JSON.parse(Native.load()).assets[0].x),'offline-B'+tag);console.log('PASS offline reload + two-device different-field merge');
 await sync(b.page);await a.context.setOffline(true);await b.context.setOffline(true);await edit(a.page,'y','conflict-A'+tag);await edit(b.page,'y','conflict-B'+tag);await a.context.setOffline(false);await sync(a.page);await b.context.setOffline(false);await sync(b.page);
 assert.ok(await b.page.evaluate(()=>OneDriveSync.status().conflicts>0));await b.page.evaluate(()=>OneDriveSync.resolveConflicts(OneDriveSync.getConflicts().map(()=> 'local')));await b.page.waitForFunction(()=>!OneDriveSync.status().busy);await sync(a.page);assert.equal(await a.page.evaluate(()=>JSON.parse(Native.load()).assets[0].y),'conflict-B'+tag);console.log('PASS same-field conflict and explicit resolution');
 const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R 4 0 R] /Count 2 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 300] /Resources << >> /Contents 5 0 R >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 300] /Resources << >> /Contents 5 0 R >>','<< /Length 0 >>\nstream\n\nendstream'];let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(pdf.length);pdf+=(i+1)+' 0 obj\n'+o+'\nendobj\n';});const xref=pdf.length;pdf+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(x=>String(x).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF';
 const uri=await a.page.evaluate(async pdf=>{const r=await fetch('/api/media/upload?kind=pdf',{method:'POST',headers:{'X-File-Name':'test.pdf'},body:pdf});const j=await r.json();const s=JSON.parse(Native.load());s.assets[0].handlingInstruction={...s.assets[0].handlingInstruction,pdfUri:j.uri,pdfName:'test.pdf'};Native.save(JSON.stringify(s));return j.uri;},pdf);await sync(a.page);
 await a.page.evaluate(uri=>WebPdfOffline.open(uri,'Test PDF'),uri);await a.page.waitForFunction(()=>document.getElementById('pdfPageInfo')?.textContent==='1 / 2');await a.page.locator('#pdfNext').click();await a.page.waitForFunction(()=>document.getElementById('pdfPageInfo')?.textContent==='2 / 2');await a.page.locator('#pdfZoomIn').click();await a.page.waitForFunction(()=>document.getElementById('pdfZoomInfo')?.textContent!=='100 %');await a.page.locator('#cancel').click();
 await a.context.setOffline(true);await a.page.evaluate(uri=>WebPdfOffline.open(uri,'Offline PDF'),uri);await a.page.waitForFunction(()=>document.querySelector('.webPdfCanvas'));await a.page.locator('#cancel').click();await a.context.setOffline(false);console.log('PASS PDF upload, internal viewer, page change, zoom and offline reopen');
 await a.page.evaluate(()=>Native.openSitePlanImage('asset-image://bundled/lageplan-gelaende.jpeg'));await a.page.waitForFunction(()=>document.querySelector('.helpImageStage img')?.naturalWidth>0);await a.page.locator('[data-zoom=in]').click();assert.notEqual(await a.page.locator('[data-zoom=reset]').innerText(),'100 %');await a.page.locator('[data-zoom=close]').click();console.log('PASS internal image viewer and zoom');
 await a.page.evaluate(()=>OneDriveSync.makeBackup());assert.equal(await a.page.evaluate(async()=>{const r=await fetch('/api/backup/read');return r.status;}),200);console.log('PASS local and simulated cloud backup');
 const before=await a.page.evaluate(()=>JSON.parse(Native.load()).assets[0].y);await edit(a.page,'y','restore-test');await sync(a.page);a.page.once('dialog',dialog=>dialog.accept());await a.page.evaluate(()=>OneDriveSync.restoreBackup());await sync(a.page);assert.equal(await a.page.evaluate(()=>JSON.parse(Native.load()).assets[0].y),before);console.log('PASS backup restore and subsequent sync with embedded PDF');
 const legacyBase=await a.page.evaluate(()=>JSON.parse(Native.load()));const legacyLocal=structuredClone(legacyBase);legacyLocal.assets[0].y='legacy'+tag;const legacy=await browser.newContext();await legacy.request.post('http://localhost:8788/api/login',{data:{password:'test-busch'}});await legacy.addInitScript(({base,local})=>{if(!localStorage.getItem('migration-test-init')){localStorage.setItem('anlagenbuch-web-v230-state',JSON.stringify(local));localStorage.setItem('anlagenbuch-web-v230-base',JSON.stringify(base));localStorage.setItem('anlagenbuch-web-v230-dirty','1');localStorage.setItem('migration-test-init','1');}},{base:legacyBase,local:legacyLocal});const lp=await legacy.newPage();await lp.goto('http://localhost:8788');await lp.waitForFunction(()=>window.OneDriveSync&&document.getElementById('webLoading').hidden);assert.equal(await lp.evaluate(()=>JSON.parse(Native.load()).assets[0].y),'legacy'+tag);assert.equal(await lp.evaluate(()=>localStorage.getItem('anlagenbuch-web-v230-state')),null);await legacy.close();console.log('PASS legacy local migration preserves pending edits');
 await a.page.locator('#dataTools').click();assert.ok(await a.page.locator('#backupButton').isVisible());assert.equal(await a.page.locator('#backupButton').innerText(),'Backup erstellen');await a.page.screenshot({path:'test-preview.png',fullPage:false});
 const extra=await a.context.newPage();await extra.goto('http://localhost:8788');await extra.waitForFunction(()=>document.getElementById('webLoading')?.textContent.includes('anderen Tab'));console.log('PASS second-tab protection');
 assert.deepEqual(errors,[]);console.log('PASS no browser JavaScript errors');
}finally{await browser.close();}
