import test from 'node:test';import assert from 'node:assert/strict';
import '../sync-merge.js';import '../core.js';import {Coordinator,AnlagenbuchSync} from '../server/coordinator.js';import {gateway} from '../server/gateway.js';
const M=globalThis.SyncMerge,clone=M.copy;
const seed=()=>AppCore.seed('A1 1 2\nA2 3 4');
class Store {allowInitialize=true;files=new Map();async read(n){return this.files.has(n)?JSON.parse(this.files.get(n)):null;}async write(n,x){this.files.set(n,JSON.stringify(x));}async get(n){return this.files.get(n)||null;}async put(n,x){this.files.set(n,x);}}
const call=(c,path,data)=>c.handle(new Request('https://example.test'+path,{method:data?'POST':'GET',headers:{'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined}));
test('Different records and fields merge, including nested units',()=>{const b=seed(),l=clone(b),r=clone(b);l.assets[0].name='Local';r.assets[0].x='9';r.assets[1].y='8';const m=M.merge(b,l,r);assert.equal(m.conflicts.length,0);assert.equal(m.state.assets[0].name,'Local');assert.equal(m.state.assets[0].x,'9');assert.equal(m.state.assets[1].y,'8');});
test('Same field conflict preserves both; deletion versus edit conflicts',()=>{const b=seed(),l=clone(b),r=clone(b);l.assets[0].name='L';r.assets[0].name='R';let m=M.merge(b,l,r);assert.equal(m.conflicts.length,1);assert.equal(m.conflicts[0].local,'L');assert.equal(m.state.assets[0].name,'R');l.assets.shift();m=M.merge(b,l,r);assert.equal(m.conflicts.length,1);assert.equal(m.conflicts[0].localMissing,true);});
test('Concurrent additions survive and identical values do not conflict',()=>{const b={rows:[],psa:['a']},l={rows:[{id:'l',x:1}],psa:['a','b']},r={rows:[{id:'r',x:2}],psa:['a','c']};const m=M.merge(b,l,r);assert.equal(m.conflicts.length,0);assert.equal(m.state.rows.length,2);assert.deepEqual(new Set(m.state.psa),new Set(['a','b','c']));assert.equal(M.merge({x:0},{x:2},{x:2}).conflicts.length,0);});
test('Offline stale clients cannot overwrite; duplicate request is idempotent',async()=>{const s=new Store(),c=new Coordinator(s),b=seed();await call(c,'/api/sync',{id:'init',base:null,local:b});const l=clone(b),r=clone(b);l.assets[0].name='L';r.assets[0].x='7';await call(c,'/api/sync',{id:'one',base:b,local:l});const result=await(await call(c,'/api/sync',{id:'two',base:b,local:r})).json();assert.equal(result.state.assets[0].name,'L');assert.equal(result.state.assets[0].x,'7');const again=await(await call(c,'/api/sync',{id:'two',base:b,local:r})).json();assert.equal(again.revision,result.revision);const conflict=clone(b);conflict.assets[0].name='X';assert.equal((await call(c,'/api/sync',{id:'three',base:b,local:conflict})).status,409);assert.equal((await s.read('state.json')).state.assets[0].name,'L');});
test('Failed OneDrive write is not acknowledged; retry survives a coordinator restart',async()=>{const s=new Store(),c=new Coordinator(s),b=seed();const write=s.write.bind(s);s.write=()=>{throw Error('offline');};await assert.rejects(call(c,'/api/sync',{id:'init',base:null,local:b}));s.write=write;const j=await(await call(new Coordinator(s),'/api/sync',{id:'init',base:null,local:b})).json();assert.equal(j.revision,1);});
test('Only one current backup and complete binary restoration',async()=>{const s=new Store(),c=new Coordinator(s),b=seed();for(const at of [1,2])assert.equal((await call(c,'/api/backup',{backup:{format:'anlagenbuch-backup-v1',at,state:b,media:{}}})).status,200);assert.equal((await s.read('backup-latest.json')).at,2);assert.equal([...s.files.keys()].filter(x=>x.startsWith('backup')).length,1);const uri='web-pdf://temp/test.pdf';await call(c,'/api/backup/media',{media:{[uri]:btoa('%PDF-test')}});assert.equal(new TextDecoder().decode(await s.get('media-test.pdf')),'%PDF-test');});
test('Gateway rejects unauthenticated and cross-origin writes',async()=>{const env={WEB_PASSWORD:'test'};assert.equal((await gateway(new Request('https://example.test/api/bootstrap'),env)).status,401);assert.equal((await gateway(new Request('https://example.test/api/sync',{method:'POST',headers:{Origin:'https://evil.test'}}),env)).status,403);const r=await gateway(new Request('https://example.test/api/login',{method:'POST',body:JSON.stringify({password:'test'})}),env);assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly/);});
test('Coordinator serializes overlapping requests across awaits',async()=>{const c=Object.create(AnlagenbuchSync.prototype);c.queue=Promise.resolve();let active=0,max=0;c.engine={handle:async()=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,5));active--;return new Response('ok');}};await Promise.all(Array.from({length:12},()=>c.fetch(new Request('https://example.test'))));assert.equal(max,1);});
test('Legacy named settings lines merge independently',()=>{const b={lines:[{name:'L1',value:0},{name:'L2',value:0}]},l=clone(b),r=clone(b);l.lines[0].value=1;r.lines[1].value=2;const m=M.merge(b,l,r);assert.equal(m.conflicts.length,0);assert.deepEqual(m.state.lines.map(x=>x.value),[1,2]);});
test('Compact local journal survives reload with pending and conflicts',()=>{const base=seed(),local=clone(base),remote=clone(base);local.assets[0].x='local';remote.assets[0].x='remote';const d={base,local,pending:{id:'pending',base:clone(base),local:clone(local)},conflicts:M.merge(base,local,remote).conflicts,conflictRemote:remote};assert.deepEqual(M.unpack(M.pack(d)),d);assert.ok(M.pack(d).length<JSON.stringify(d).length);});

test('Delayed retry after 200 other writes cannot resurrect a deleted record',async()=>{
 const store=new Store(),c=new Coordinator(store),base=seed();
 await call(c,'/api/sync',{id:'init',base:null,local:base});
 const local=clone(base);local.assets.push({...clone(base.assets[0]),id:'new-record',name:'New'});
 const pending={id:'lost-response',base,local};
 await call(c,'/api/sync',pending);
 await call(c,'/api/sync',{id:'delete',base:local,local:base});
 for(let i=0;i<205;i++)await call(c,'/api/sync',{id:'other-'+i,base,local:base});
 const before=await store.read('state.json');
 const result=await(await call(new Coordinator(store),'/api/sync',pending)).json();
 assert.equal(result.revision,before.revision);
 assert.equal(result.state.assets.some(a=>a.id==='new-record'),false);
});
