'use strict';
const ROOT='/Busch Group/Anlagenbuch';
const APP='atbkt1j41dvg8z1';
const BACKUP=/^backup-([0-9]+)-[A-Za-z0-9-]+\.json$/;
const EVENT=/^event-([0-9]+)-([A-Za-z0-9-]{1,100})\.json$/;
const JSQR_URL='https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.js';
const PDFJS_BASE='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/legacy/build/';
const JSQR_SHA256='bc40c8a15196236b2314db0856f72ca0b49980cd5413b8c852a7349f5fee0859';
let tokenCache={token:'',exp:0},jsqrCache=null,pdfjsCache={},companionCache={at:0,data:null};
const enc=new TextEncoder(),dec=new TextDecoder();
function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8',...extra}});}
function b64urlDecode(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const bin=atob(s),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return dec.decode(u);}
function team(env){const code=String(env.DROPBOX_TEAM_CODE||'').trim();if(!/^AB1-[A-Za-z0-9_-]+$/.test(code))throw Error('DROPBOX_TEAM_CODE fehlt oder ist ungültig.');const c=JSON.parse(b64urlDecode(code.slice(4)));if(c.v!==1||c.app!==APP||!c.refresh)throw Error('Der Firmenzugang gehört nicht zu dieser Anlagenbuch-App.');return c;}
async function access(env,force=false){if(!force&&tokenCache.token&&tokenCache.exp>Date.now()+60000)return tokenCache.token;const c=team(env),body=new URLSearchParams({grant_type:'refresh_token',refresh_token:c.refresh,client_id:APP}),r=await fetch('https://api.dropboxapi.com/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw Error('Dropbox-Anmeldung fehlgeschlagen ('+r.status+').');const t=await r.json();tokenCache={token:t.access_token,exp:Date.now()+(t.expires_in||14400)*1000};return tokenCache.token;}
async function dbx(env,endpoint,args,bytes,retry=true){const content=endpoint==='files/upload'||endpoint==='files/download';const headers={Authorization:'Bearer '+await access(env)};let body;if(content){headers['Dropbox-API-Arg']=JSON.stringify(args);if(bytes!==undefined){headers['Content-Type']='application/octet-stream';body=bytes;}}else{headers['Content-Type']='application/json';body=JSON.stringify(args);}const r=await fetch(`https://${content?'content':'api'}.dropboxapi.com/2/${endpoint}`,{method:'POST',headers,body});if(r.status===401&&retry){await access(env,true);return dbx(env,endpoint,args,bytes,false);}if(!r.ok){const e=Error('Dropbox-Abgleich fehlgeschlagen ('+r.status+').');e.status=r.status;if(r.status===429){const ra=Number(r.headers.get('Retry-After')||0);e.retryAfter=Math.max(10,Math.min(300,Number.isFinite(ra)&&ra>0?ra:30));}throw e;}if(endpoint==='files/download')return {bytes:new Uint8Array(await r.arrayBuffer()),meta:JSON.parse(r.headers.get('dropbox-api-result')||'{}')};return r.json();}
async function ensure(env,path){try{await dbx(env,'files/get_metadata',{path});}catch(e){if(e.status!==409)throw e;await dbx(env,'files/create_folder_v2',{path,autorename:false});}}
async function list(env,path,cursor=''){let page=await dbx(env,cursor?'files/list_folder/continue':'files/list_folder',cursor?{cursor}:{path,recursive:false,limit:2000}),entries=[...(page.entries||[])];while(page.has_more){page=await dbx(env,'files/list_folder/continue',{cursor:page.cursor});entries.push(...(page.entries||[]));}return {entries,cursor:page.cursor};}
async function listMaybe(env,path,cursor=''){try{return await list(env,path,cursor);}catch(e){if(e.status===409)return {entries:[],cursor:''};throw e;}}
async function upload(env,path,bytes){return dbx(env,'files/upload',{path,mode:'overwrite',autorename:false,mute:true},bytes);}
async function download(env,path){return (await dbx(env,'files/download',{path})).bytes;}
async function deleteBatch(env,paths){for(let i=0;i<paths.length;i+=1000){const entries=paths.slice(i,i+1000).map(path=>({path}));if(!entries.length)continue;await dbx(env,'files/delete_batch',{entries});}}
async function pruneOldBackups(env){const root=await list(env,ROOT),backs=backupRows(root.entries);if(backs.length<=1)return backs[0]||null;const keep=backs[0],paths=[];for(const b of backs.slice(1)){paths.push(b.path);paths.push(ROOT+'/PDF-Sicherungen/'+b.id.slice(0,-5));}try{await deleteBatch(env,paths);}catch(_){/* Backup itself is already confirmed; cleanup is retried after the next successful backup. */}return keep;}
function safeName(s){s=String(s||'');if(!/^[A-Za-z0-9._-]{1,220}$/.test(s)||s==='.'||s==='..')throw Error('Ungültiger Dateiname.');return s;}
function clone(v){return JSON.parse(JSON.stringify(v));}
function newer(a,b){return !!a&&(!b||a.at>b.at||(a.at===b.at&&String(a.eventId)>String(b.eventId)));}
function applyEvents(s,events,type){const rowKey=type==='fault'?'fault':'note',listKey=type==='fault'?'faults':'notes',metaKey=type==='fault'?'faultSyncMeta':'workSyncMeta';s[metaKey]=s[metaKey]||{};for(const e of [...events].sort((a,b)=>a.at-b.at||String(a.eventId).localeCompare(String(b.eventId)))){if(!e||e.schema!==1||!['upsert','delete'].includes(e.op)||!e.asset?.id||!e[rowKey]?.id||!Number.isFinite(e.at)||typeof e.eventId!=='string')continue;const id=e[rowKey].id,m=s[metaKey][id];if(!newer(e,m)&&!(m&&m.at===e.at&&m.eventId===e.eventId&&!m.deleted&&!s.assets.some(a=>(a[listKey]||[]).some(r=>r.id===id))))continue;for(const a of s.assets)a[listKey]=(a[listKey]||[]).filter(r=>r.id!==id);if(e.op!=='delete'){let a=s.assets.find(a=>a.id===e.asset.id);if(!a){a={...e.asset,notes:[],faults:[]};s.assets.push(a);if(!s.modules.includes(a.module))s.modules.push(a.module);}a[listKey].push(clone(e[rowKey]));}s[metaKey][id]={at:e.at,eventId:e.eventId,deleted:e.op==='delete',assetId:e.asset.id};}return s;}
function backupRows(entries){return entries.filter(x=>x['.tag']==='file'&&BACKUP.test(x.name)).map(x=>({id:x.name,path:x.path_display||x.path_lower,at:Number(x.name.match(BACKUP)[1]),size:x.size||0})).sort((a,b)=>b.at-a.at);}
async function recentEventsFromEntries(env,entries,since){const rows=entries.filter(x=>x['.tag']==='file'&&EVENT.test(x.name)&&Number(x.name.match(EVENT)[1])>=since),out=[];for(let i=0;i<rows.length;i+=16){const batch=rows.slice(i,i+16);const got=await Promise.all(batch.map(async f=>{try{return JSON.parse(dec.decode(await download(env,f.id||f.path_display)));}catch(_){return null;}}));for(const e of got)if(e)out.push(e);}return out;}
async function latestState(env){await ensure(env,ROOT);const root=await list(env,ROOT),backs=backupRows(root.entries);let state='',latestAt=0;if(backs[0]){state=dec.decode(await download(env,backs[0].path));latestAt=backs[0].at;}let parsed=null;try{parsed=state?JSON.parse(state):null;}catch(_){parsed=null;}const since=Math.max(0,latestAt-300000),faultList=await listMaybe(env,ROOT+'/Sync/Stoerungen'),workList=await listMaybe(env,ROOT+'/Sync/Arbeiten'),faults=await recentEventsFromEntries(env,faultList.entries,since),work=await recentEventsFromEntries(env,workList.entries,since);if(parsed&&Array.isArray(parsed.assets)&&Array.isArray(parsed.modules)){applyEvents(parsed,faults,'fault');applyEvents(parsed,work,'work');state=JSON.stringify(parsed);}return {state,latestAt,backups:backs.slice(0,30),backupCursor:root.cursor,faultCursor:faultList.cursor,workCursor:workList.cursor};}
function parseMedia(uri){const u=new URL(uri),bits=u.pathname.split('/').filter(Boolean).map(decodeURIComponent);if((u.protocol==='app-pdf:'||u.protocol==='app-image:')&&u.hostname==='backup'&&bits.length===2&&BACKUP.test(bits[0]))return {path:ROOT+'/PDF-Sicherungen/'+bits[0].slice(0,-5)+'/'+safeName(bits[1]),file:safeName(bits[1])};if((u.protocol==='web-pdf:'||u.protocol==='web-image:')&&u.hostname==='temp'&&bits.length===1)return {path:ROOT+'/Web-Temp/'+safeName(bits[0]),file:safeName(bits[0])};throw Error('Dateiverweis ist ungültig.');}
async function currentInstructionMedia(env,attachmentId){const id=String(attachmentId||'');if(!/^[A-Za-z0-9._-]{1,160}$/.test(id))throw Error('Ungültige PDF-ID.');const root=await list(env,ROOT),backs=backupRows(root.entries);if(!backs[0])throw Error('Keine aktuelle Sicherung vorhanden.');const snap=JSON.parse(dec.decode(await download(env,backs[0].path))),row=(snap.instructionLibrary||[]).find(x=>x&&x.id===id&&x.attachmentOnly&&x.pdfUri);if(!row)throw Error('PDF ist in der aktuellen Sicherung nicht verknüpft.');const m=parseMedia(row.pdfUri),b=await download(env,m.path);return {m,b};}
function extOf(name,kind){const m=String(name||'').toLowerCase().match(/\.(pdf|png|jpg|jpeg|webp)$/);if(m)return'.'+m[1];return kind==='sitePlan'?'.png':'.pdf';}
async function buildBackup(env,raw,requestedAt){let s=JSON.parse(raw);if(!s||!Array.isArray(s.assets)||!Array.isArray(s.modules))throw Error('Ungültiger Anlagen-Datenstand.');const now=Date.now(),at=now,id='backup-'+at+'-'+crypto.randomUUID()+'.json',dest=ROOT+'/PDF-Sicherungen/'+id.slice(0,-5),manifest=[];await ensure(env,ROOT);await ensure(env,ROOT+'/PDF-Sicherungen');await ensure(env,dest);s=clone(s);
 let fallbackState=null,fallbackLoaded=false;
 const fallbackUri=async(kind,identity)=>{if(!fallbackLoaded){fallbackLoaded=true;try{const r=await list(env,ROOT),b=backupRows(r.entries)[0];if(b)fallbackState=JSON.parse(dec.decode(await download(env,b.path)));}catch(_){fallbackState=null;}}if(!fallbackState)return'';if(kind==='library')return String((fallbackState.instructionLibrary||[]).find(x=>x&&x.id===identity.instructionId)?.pdfUri||'');if(kind==='asset')return String((fallbackState.assets||[]).find(x=>x&&x.id===identity.assetId)?.handlingInstruction?.pdfUri||'');if(kind==='sitePlan')return String(fallbackState.sitePlan?.imageUri||'');return'';};
 const add=async(obj,kind,key,identity)=>{const uri=obj?.[key];if(!uri)return;let src;try{src=parseMedia(uri);}catch(e){if(String(uri).startsWith('asset-image://bundled/'))return;throw e;}let bytes=null,sourceFile=src.file;try{bytes=await download(env,src.path);}catch(e){if(e.status!==409)throw e;const alt=await fallbackUri(kind,identity);if(alt){try{const p=parseMedia(alt);bytes=await download(env,p.path);sourceFile=p.file;}catch(_){} }if(!bytes){obj[key]='';return;}}const file=kind+'__'+crypto.randomUUID()+extOf(sourceFile,kind);await upload(env,dest+'/'+file,bytes);manifest.push({kind,...identity,file,size:bytes.length,pdfName:obj.pdfName||'Anweisung.pdf',imageName:obj.imageName||'Lageplan'});obj[key]=`app-${kind==='sitePlan'?'image':'pdf'}://backup/${id}/${file}`;};
 for(const i of s.instructionLibrary||[])await add(i,'library','pdfUri',{instructionId:i.id,title:i.title,assignedAssets:[]});for(const a of s.assets||[])await add(a.handlingInstruction,'asset','pdfUri',{assetId:a.id,assetName:a.name});await add(s.sitePlan,'sitePlan','imageUri',{});const stateRaw=JSON.stringify(s);await upload(env,dest+'/manifest.json',enc.encode(JSON.stringify({createdAt:Date.now(),pdfs:manifest})));await upload(env,ROOT+'/'+id,enc.encode(stateRaw));const keep=await pruneOldBackups(env),row=keep||{id,path:ROOT+'/'+id,at,size:enc.encode(stateRaw).length};return {id:row.id||id,at:row.at||at,backups:[row]};}
async function hmac(password,text){const key=await crypto.subtle.importKey('raw',enc.encode(password),{name:'HMAC',hash:'SHA-256'},false,['sign']),sig=new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(text)));return [...sig].map(b=>b.toString(16).padStart(2,'0')).join('');}
function cookie(req,name){const raw=req.headers.get('cookie')||'';for(const p of raw.split(';')){const [k,...v]=p.trim().split('=');if(k===name)return v.join('=');}return'';}
async function authorized(req,env){const pw=String(env.WEB_PASSWORD||'');if(!pw)return false;const t=cookie(req,'ab_session'),m=t.match(/^(\d+)\.([0-9a-f]{64})$/);if(!m||Number(m[1])<Date.now())return false;return (await hmac(pw,m[1]))===m[2];}
function berlinDate(){try{return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()).replace(/\//g,'-');}catch(_){return new Date().toISOString().slice(0,10);}}
async function companionStatus(env){if(companionCache.data&&Date.now()-companionCache.at<15000)return companionCache.data;const x=await latestState(env);let s={assets:[],dailyBusiness:[]};try{s=x.state?JSON.parse(x.state):s;}catch(_){}const open=[],progress=[];for(const a of (s.assets||[]))for(const f of (a.faults||[])){if(f.status==='open')open.push({id:f.id,assetId:a.id,assetName:a.name||'',description:f.description||'',reportedAt:f.reportedAt||'',unitName:f.unitBarcode||f.unitName||''});else if(f.status==='in_progress')progress.push({id:f.id,assetId:a.id,assetName:a.name||'',description:f.description||'',updatedAt:f.updatedAt||'',unitName:f.unitBarcode||f.unitName||''});}const today=berlinDate(),todayCount=(s.dailyBusiness||[]).filter(r=>r&&r.date===today&&!r.done).length;const data={ok:true,serverTime:Date.now(),openCount:open.length,progressCount:progress.length,todayCount,openFaultIds:open.map(x=>x.id),openFaults:open.slice(-20),latestAt:x.latestAt||0};companionCache={at:Date.now(),data};return data;}
async function companionAuthorized(req,env){const pw=String(env.WEB_PASSWORD||''),got=String(req.headers.get('X-Anlagenbuch-Password')||'');return !!pw&&got===pw;}
async function persistentSessionCookie(env){const pw=String(env.WEB_PASSWORD||'');if(!pw)return'';const maxAge=365*24*3600,exp=Date.now()+maxAge*1000,t=exp+'.'+await hmac(pw,String(exp));return `ab_session=${t}; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=${maxAge}`;}
async function companionHandoffUrl(req,env){const pw=String(env.WEB_PASSWORD||'');if(!pw)throw Error('WEB_PASSWORD ist noch nicht eingerichtet.');const exp=Date.now()+90000,sig=await hmac(pw,'handoff:'+exp),u=new URL('/companion-auth',req.url);u.searchParams.set('token',exp+'.'+sig);return u.toString();}
async function verifyCompanionHandoff(token,env){const pw=String(env.WEB_PASSWORD||''),m=String(token||'').match(/^(\d+)\.([0-9a-f]{64})$/);if(!pw||!m)return false;const exp=Number(m[1]),now=Date.now();if(!Number.isFinite(exp)||exp<now||exp>now+120000)return false;return (await hmac(pw,'handoff:'+m[1]))===m[2];}
async function login(req,env){const pw=String(env.WEB_PASSWORD||'');if(!pw)return json({ok:false,error:'WEB_PASSWORD ist noch nicht eingerichtet.'},503);let body;try{body=await req.json();}catch(_){return json({ok:false,error:'Ungültige Anmeldung.'},400);}if(String(body.password||'')!==pw)return json({ok:false,error:'Passwort ist nicht richtig.'},401);return json({ok:true},200,{'Set-Cookie':await persistentSessionCookie(env)});}
function securityHeaders(h=new Headers()){h.set('Cache-Control','no-store, no-cache, must-revalidate, max-age=0');h.set('Pragma','no-cache');h.set('X-Content-Type-Options','nosniff');h.set('Referrer-Policy','no-referrer');h.set('X-Frame-Options','DENY');h.set('Cross-Origin-Opener-Policy','same-origin');h.set('Cross-Origin-Resource-Policy','same-origin');h.set('Permissions-Policy','camera=(self), microphone=(), geolocation=()');h.set('X-Robots-Tag','noindex, nofollow, noarchive');h.set('Content-Security-Policy',"default-src 'self'; img-src 'self' data: blob:; media-src 'self' blob:; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; object-src 'none'; frame-src 'self' blob:; base-uri 'none'; frame-ancestors 'none'; form-action 'self'");return h;}
async function staticResponse(req,env,path){const u=new URL(req.url);u.pathname=path||u.pathname;const r=await env.ASSETS.fetch(new Request(u.toString(),{method:'GET',headers:req.headers}));return new Response(r.body,{status:r.status,statusText:r.statusText,headers:securityHeaders(new Headers(r.headers))});}
async function jsqr(){if(jsqrCache)return jsqrCache;const r=await fetch(JSQR_URL);if(!r.ok)throw Error('QR-Bibliothek konnte nicht geladen werden.');const b=new Uint8Array(await r.arrayBuffer()),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('');if(hash!==JSQR_SHA256)throw Error('QR-Bibliothek hat eine unerwartete Prüfsumme.');jsqrCache=b;return b;}
async function pdfjsAsset(name){if(!['pdf.min.js','pdf.worker.min.js'].includes(name))throw Error('Ungültige PDF.js-Datei.');if(pdfjsCache[name])return pdfjsCache[name];const r=await fetch(PDFJS_BASE+name);if(!r.ok)throw Error('Interner PDF-Viewer konnte nicht geladen werden ('+r.status+').');const b=new Uint8Array(await r.arrayBuffer());pdfjsCache[name]=b;return b;}
async function api(req,env,url){if(url.pathname==='/api/login'&&req.method==='POST')return login(req,env);if(url.pathname==='/api/companion/handoff'&&req.method==='GET'){if(!(await companionAuthorized(req,env)))return json({ok:false,error:'Begleiter-Passwort ist nicht richtig.'},401);try{return json({ok:true,url:await companionHandoffUrl(req,env)});}catch(e){return json({ok:false,error:e.message||String(e)},400);}}if(url.pathname==='/api/companion/status'&&req.method==='GET'){if(!(await companionAuthorized(req,env)))return json({ok:false,error:'Begleiter-Passwort ist nicht richtig.'},401);try{return json(await companionStatus(env));}catch(e){if(e&&e.status===429){const retryAfter=Math.max(15,Math.min(300,Number(e.retryAfter)||30));return json({ok:false,error:e.message||String(e),retryAfter},429,{'Retry-After':String(retryAfter)});}return json({ok:false,error:e.message||String(e)},400);}}try{if(!(await authorized(req,env)))return json({ok:false,error:'Anmeldung erforderlich.'},401);
  if(url.pathname==='/api/logout'&&req.method==='POST')return json({ok:true},200,{'Set-Cookie':'ab_session=; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=0','Clear-Site-Data':'"cache", "cookies", "storage"'});
  if(url.pathname==='/api/bootstrap'&&req.method==='GET'){const x=await latestState(env);return json({ok:true,...x,serverTime:Date.now()});}
  if((url.pathname==='/api/save-state'||url.pathname==='/api/backup')&&req.method==='POST'){const body=await req.json();if(typeof body.raw!=='string'||body.raw.length>24*1024*1024)throw Error('Sicherung ist ungültig oder zu groß.');{const saved=await buildBackup(env,body.raw,body.at);return json({ok:true,...saved},200,{'X-Anlagenbuch-Handler':'save-state-2.76'});}}
  if(url.pathname==='/api/backups'&&req.method==='GET'){const root=await list(env,ROOT);return json({ok:true,backups:backupRows(root.entries).slice(0,50),cursor:root.cursor});}
  if(url.pathname==='/api/backups/changes'&&req.method==='GET'){const c=url.searchParams.get('cursor')||'';if(!c)return json({ok:false,error:'Cursor fehlt.'},400);const page=await listMaybe(env,ROOT,c);return json({ok:true,changes:backupRows(page.entries),cursor:page.cursor});}
  if(url.pathname==='/api/backup/read'&&req.method==='GET'){const p=url.searchParams.get('path')||'',name=p.split('/').pop();if(!p.startsWith(ROOT+'/')||!BACKUP.test(name))throw Error('Ungültige Sicherung.');return json({ok:true,id:name,raw:dec.decode(await download(env,p))});}
  if(url.pathname==='/api/events/push'&&req.method==='POST'){const body=await req.json(),type=body.type;if(!['fault','work'].includes(type))throw Error('Ungültiger Ereignistyp.');const rows=Array.isArray(body.events)?body.events:[],folder=ROOT+'/Sync/'+(type==='fault'?'Stoerungen':'Arbeiten');await ensure(env,ROOT);await ensure(env,ROOT+'/Sync');await ensure(env,folder);for(const e of rows){if(!e?.eventId||!Number.isFinite(e.at)||!/^[A-Za-z0-9-]{1,100}$/.test(e.eventId))continue;await upload(env,`${folder}/event-${e.at}-${e.eventId}.json`,enc.encode(JSON.stringify(e)));}return json({ok:true,count:rows.length});}
  if(url.pathname==='/api/events/pull'&&req.method==='GET'){const type=url.searchParams.get('type'),folder=ROOT+'/Sync/'+(type==='fault'?'Stoerungen':'Arbeiten');if(!['fault','work'].includes(type))throw Error('Ungültiger Ereignistyp.');const cursor=url.searchParams.get('cursor')||'';const page=await listMaybe(env,folder,cursor),events=await recentEventsFromEntries(env,page.entries,0);return json({ok:true,events,cursor:page.cursor});}
  if(url.pathname==='/api/media/upload'&&req.method==='POST'){const kind=url.searchParams.get('kind');if(!['pdf','image'].includes(kind))throw Error('Ungültiger Medientyp.');const b=new Uint8Array(await req.arrayBuffer());if(!b.length||b.length>50*1024*1024)throw Error('Datei ist leer oder größer als 50 MB.');const original=decodeURIComponent(req.headers.get('X-File-Name')||'Datei'),ext=kind==='pdf'?'.pdf':extOf(original,'sitePlan');if(kind==='pdf'&&dec.decode(b.slice(0,1024)).indexOf('%PDF-')<0)throw Error('Keine gültige PDF-Datei.');await ensure(env,ROOT);await ensure(env,ROOT+'/Web-Temp');const file=crypto.randomUUID()+ext;await upload(env,ROOT+'/Web-Temp/'+file,b);return json({ok:true,uri:`web-${kind==='pdf'?'pdf':'image'}://temp/${file}`,name:original});}
  if(url.pathname==='/api/media'&&req.method==='GET'){const uri=url.searchParams.get('uri')||'',attachmentId=url.searchParams.get('id')||'';let m,b;try{m=parseMedia(uri);b=await download(env,m.path);}catch(firstError){if(!attachmentId)throw firstError;const recovered=await currentInstructionMedia(env,attachmentId);m=recovered.m;b=recovered.b;}const ext=extOf(m.file,'sitePlan'),ct=ext==='.pdf'?'application/pdf':ext==='.png'?'image/png':ext==='.webp'?'image/webp':'image/jpeg';return new Response(b,{headers:securityHeaders(new Headers({'Content-Type':ct,'Content-Disposition':'inline','X-Anlagenbuch-Media':'ok'}))});}
  if(url.pathname==='/api/health'&&req.method==='GET'){await access(env);return json({ok:true,dropbox:true});}
  return json({ok:false,error:'Unbekannte Web-Funktion.'},404);
 }catch(e){if(e&&e.status===429){const retryAfter=Math.max(10,Math.min(300,Number(e.retryAfter)||30));return json({ok:false,error:e.message||String(e),retryAfter},429,{'Retry-After':String(retryAfter)});}return json({ok:false,error:e.message||String(e)},400);}}

export async function onRequest(context){
  const req=context.request, env=context.env, url=new URL(req.url);
  try{
    if(url.pathname==='/api/version') return json({ok:true,version:'2.78',mode:'pages-functions-routed'});
    if(url.pathname.startsWith('/api/')) return await api(req,env,url);
    return json({ok:false,error:'API route not found.'},404);
  }catch(e){
    return json({ok:false,error:'API-Fehler: '+String(e&&e.message||e),version:'2.78'},500,{'X-Anlagenbuch-Handler':'pages-functions-2.77'});
  }
}
